### ISSUE TITLE
Allow adding of rolling Tool Kits.

### ISSUE THREAD

**Issue by Ikabodo** [AngryBeaver/beavers-crafting#1]
It would make sense to be able to roll for tools instead of skills. :)

**Comment by Steelskinz** [comment]
I second this. That was fast I was about to write about it.

**Comment by iotech-fvtt** [comment]
I'd like to see this too, or have a tool/tool kit required (like an ingredient) but not destroyed on failure.

**Comment by AngryBeaver** [comment]
I will add this next.

(@iotech-fvtt)
(you broke your tools) will not come with this. That is to specific for mainstream so this seems to be more a feautre for advanced users when i invent the crafting macro you then should be able to manipulate the result in a way that produces what you want.

**Comment by AngryBeaver** [comment]
done 0.5.x
