### ISSUE TITLE
[Feature] choose item for ingredient any item

### ISSUE THREAD

**Issue by rinnocenti** [AngryBeaver/beavers-crafting#10]
pretty straightforward, in the placeholder of any item, being able to choose (drag an item that matches) and change the an for the item.

**Comment by AngryBeaver** [comment]
yes, that was the intention when i choose the picture for anyOf with the surounding dots but got too lazy to finally implement it. This will definitivly get my attention as soon as i find some time to code again, i cant make any better promises.

**Comment by AngryBeaver** [comment]
your request got me motivated enough to finally add this feature. It is out with version 0.6.0. But it also showed me that this wont be the end to anyOf, probably the next thing here would be that the macro also can return a response that i then should popup when you drag a wrong ingredient into it. But not for now, some day in the future.

for now we have customized AnyOf ingredient:
https://github.com/AngryBeaver/beavers-crafting/blob/main/changelog.md
