### ISSUE TITLE
[QUESTION API] How to set some additional flags on the result item with the API 

### ISSUE THREAD

**Issue by p4535992** [AngryBeaver/beavers-crafting#103]
Hi I'm trying to understand how the API works, I created a code to retrieve the ItemTags module flags from one of the components set as "consumed" and to transfer them to the "produced" component, but it doesn't seem to work can you help me ?

```
// Assuming recipeData.input is the object containing the ingredient containers
const ingredientContainers = Object.values(recipeData.input);

// Use an async function to handle the asynchronous nature of fromUuid or a similar function
async function processIngredients() {
  for (const ingredientContainer of ingredientContainers) {
    // Access the ingredient details, which is the first property of the container object
    const ingredientDetails = ingredientContainer[Object.keys(ingredientContainer)[0]];

    // Check if the ingredient's name contains 'Ingot'
    if (ingredientDetails.name && ingredientDetails.name.includes('Ingot')) {
      try {
        // Retrieve the document from the UUID
        const document = await fromUuid(ingredientDetails.uuid);

        // Now we have the document, we can retrieve the tags
        const tags = ItemTags.Get(document);

        // Log the tags or a message if no tags are found
        if (tags) {
          console.log(`Tags for ${ingredientDetails.name}:`, tags);
        } else {
          console.log(`No tags found for ${ingredientDetails.name}`);
        }
		return tags;
      } catch (error) {
        console.error(`Error retrieving document for ${ingredientDetails.name}:`, error);
      }
    }
  }
}

const currentTags = await processIngredients();
console.log(currentTags);

if(!result.hasError()){
  console.log(`TS All Results |`, result);
  if(recipeData.components?.length <= 0){
	  console.warn(`TS All Results | is empty`);
	  return;
  }
  const output1 = Object.values(recipeData.output)[0];
  result.updateComponent("produced",output1,
	  (componentResult, quantity) => {
		componentResult.userInteraction = "onSuccess"
                // The item no exists yet
		//const uuidResult = componentResult.uuid;
		//const documentResult = fromUuidSync(uuidResult);
		//ItemTags.Set(documentResult, currentTags);
               
                // Yea this is not working maybe a simple post hook at the 100% is a simplier solution ?
		setProperty(componentResult.component,`flags.item-tags.tags`, currentTags);
  });
}
```

My 99% use cases are about updating the result that is created arrived at 100%, but do you think it is worthwhile to put a hook listening when it arrives at 100% ? For my use case it would be more than enough.

**Comment by AngryBeaver** [comment]
###TODO
yeah i can add some hooks i guess. I will think about it.

### Meanwhile
The componentModell might rejecting everything it does not know if it get clones ore recrated on its procssing way  but you can extend the componentModell.
You would need something like this.
`
Hooks.once("beavers-system-interface.ready", async function(){
   beaversSystemInterface.addExtension("item-tags",{componentAddFlags:["tags"]})
}
`
and i think this [line ](https://github.com/AngryBeaver/beavers-system-interface/blob/main/src/CoreSystem.ts#L398)here would then add it.

**Comment by AngryBeaver** [comment]
be carefull you will soon again run into the problem that then next you want to differentiate between items with diffrent tags else it might stack it to others that should not have that tags set.

Then you would need to tinker with an extended isSame for this flagg :-)

**Comment by AngryBeaver** [comment]
Also when you use the above hook you also store this tag information on recipes you then will create after this extension is enabled. 

e.g. When you created a recipe with an output the tags are serialized into the recipe and when you afterwards add or remove tags from the original output, it might be that the line shown above will overwrite what is loaded from origin object with what you had serialized into your recipe.

**Comment by AngryBeaver** [comment]
so just have tested my code and observed that my module does not behave like i was expecting turns out setProperty of foundry is not creating necessary deep structures. So that recipes serialized the flag had not been true -> BSI: 2.1.9 now it is as it should.

![image](https://github.com/AngryBeaver/beavers-crafting/assets/10677192/2ae30466-b1e8-4704-bcf3-314bfb86692c)

**Comment by p4535992** [comment]
wait `setProperty` is bugged or is it just a special case ? ? Is this something I should open an issue on foundry for ?

**Comment by AngryBeaver** [comment]
well yes probably a bug :-)
![image](https://github.com/AngryBeaver/beavers-crafting/assets/10677192/6c1c288e-5657-4bd9-93d6-b21ad576d7fb)

**Comment by AngryBeaver** [comment]
I do not think a Hook here will help you much i will provide an undocumented one as it wont hurt me much:
called "beavers-crafting.processed" and has {recipe: Recipe, result: Result, processed: ItemChange }

The itemChange contains created, updated, deleted items !BUT! of the complete process you would need some logic to gather what you really want. E.g. in the processEnd step i will return ingredients when they are not consumed in the process -> those and the produced items might end up in the created stack or the updated stack (which ever it is for the actor).

**Comment by p4535992** [comment]
Ty for the hook i will check out this week end!

For the `setProperty` thing i have open a issue on the foundry project if you are interested https://github.com/foundryvtt/foundryvtt/issues/10310

then sorry one question is it possible to use the API to increase the difficulty of the dc when the roll is rolled ? Basically is I am trying to solve with the use of the API the issue mentioned here:

https://github.com/AngryBeaver/beavers-crafting/issues/79

from what you say it should be possible using module interfaces, but I couldn't... can you give me an example  ?

P.S. again in my ignorance not to break you too much on your side I would say that a hook to customize the value of the DC , (when you click on the "play" button to understand each other) maybe is the easiest solution ?

**Comment by AngryBeaver** [comment]
3.4.1. Released.
I will close this now. Your latest request will be tracked in the linked other issue.
