### ISSUE TITLE
feature request: add options to rename character sheet tab and recipe compendium

### ISSUE THREAD

**Issue by JenniferPylko** [AngryBeaver/beavers-crafting#106]
your module works really well for things other than crafting, like skill trees and spell lists (here are some examples of how i'm using it)

![image](https://github.com/AngryBeaver/beavers-crafting/assets/3450413/487f07c1-ec85-4a3d-b6db-a821aeb6fcd5)

![image](https://github.com/AngryBeaver/beavers-crafting/assets/3450413/0590ce87-57e7-4c43-8a2a-85a60e0b7aac)

it would be super neat if there were settings to change the name of the character sheet tab and recipe compendium to more generic things, like "Progression" or "Unlockables"

right now i'm patching `game.translations` to achieve this, but that's pretty hacky and official support via a setting would be preferable

thanks for all your work on this module!

**Comment by AngryBeaver** [comment]
Oh well nice. You are right, you can do so many things with it now that it shouldn't even be calle beavers-crafting but it is too late for that now. 

I will make the tab editable and i should probably make the various usecases more prominent somehow. May I use your screenshot for that in my documentation ?

**Comment by JenniferPylko** [comment]
absolutely!

**Comment by AngryBeaver** [comment]
3.4.1 released
It will not yet cover Beaver's Recipe Compendium. For now it keeps the name Recipe. It is hard when everything is generic that anyone can follow a documentation while i can't name what i am talking about. At somepoint Recipe may be replaced with blueprint, draft or concept or i do not yet know. I have no good idea for a clear name.
