### ISSUE TITLE
[Feature] Recipes that do not spend item.

### ISSUE THREAD

**Issue by rinnocenti** [AngryBeaver/beavers-crafting#11]
I know it wouldn't be a recipe, it would be more of a blueprint.
But it would be interesting to have some reusable items to create some blue prints, like a camp where the character needs to have some items in his backpack, but he wouldn't lose these items.

**Comment by AngryBeaver** [comment]
Sounds similar to this feature request "https://github.com/AngryBeaver/beavers-crafting/issues/7". So you end up haveing a list of items that are required next to tools but are not consumed.

Both could be managed, when i implement custom macros, but wouldn't be a nice userexperience. Anyway custom macro has higher prio to me, so if need be i would come back to this thereafter.

**Comment by AngryBeaver** [comment]
Added with 0.7.x attendants:
https://github.com/AngryBeaver/beavers-crafting/blob/main/changelog.md
