### ISSUE TITLE
bug: anyof code editor doesn't render if saved with a syntax error in the code

### ISSUE THREAD

**Issue by JenniferPylko** [AngryBeaver/beavers-crafting#110]
i imagine this'll be a relatively simple fix of adding a try/catch in the render function
![image](https://github.com/AngryBeaver/beavers-crafting/assets/3450413/9e56fad8-f2bc-4dec-8507-bce6c9620db0)

**Comment by AngryBeaver** [comment]
i would need more details: ( i asume dnd5e ? )
usually there is some kind of try catch: 
![image](https://github.com/AngryBeaver/beavers-crafting/assets/10677192/6206f57f-ba73-4239-94a3-c97b23b6ecf8)

**Comment by JenniferPylko** [comment]
try setting the code to `await "if (item.parent.constructor.name === "Actor5e") {`, test an item, close the anyof item, then re-open the anyof item

**Comment by AngryBeaver** [comment]
thx that is reproduceable i will have a look tomorrow.

**Comment by AngryBeaver** [comment]
should be fixed in 3.4.2
