### ISSUE TITLE
request - Start hook?

### ISSUE THREAD

**Issue by tirzah2** [AngryBeaver/beavers-crafting#113]
Hi!
i'm not sure if its possible already, but i was wondering if there was a hook for when someone clicks on Start (in the crafting app) and before it adds the item to be crafted in the character sheet. 

Basically what i would like to do is for every recipe to have all the same advanced macro, but without having to add the macro manually to each recipe i created and every recipe i will create from now on.

this way i could create a world script.. something like: hooks.on(beaverscraftingStart... etcetc..)
i know there is a hook (i think is processed) for when the item is crafted..

**Comment by AngryBeaver** [comment]
There is official no such hook :-) especially no processed Hook.
 
Does it also have to do with tags ? I have the feeling you all try to do exaclty the same at the exact same time, its amazing.

So what i could provide and might become official is a hook?/setting to register a macro that will run prior to the macro execution time.

So this can then basically run globally for all recipes which makes it mostly useless... -> so probably it comes with some recipe filtering where this macro is available at.

I will think about it.

BUT still if you want this for itemTagger this alone will not help.
 Read here: https://github.com/AngryBeaver/beavers-crafting/issues/103

**Comment by tirzah2** [comment]
basically i would like to add to each recipe to check if any of the input also appears in a rolltable with a DC modifier. 
So for example if im using ingot steel and ingot adamant to craft a dagger, it checks a rolltable if ingot steel and ingot adamant have dc modifiers (in this case +2 and +3), then all the checks made to make the dagger will have a +5.
i think is generic enough to be used as a world script if there was a hook for precrafting, cause otherwise i need to add this to each recipe.

`if (recipeData && recipeData.tests && recipeData.input) {
  // Retrieve the roll table called 'minerali'
  let rollTable = game.tables.getName('minerali');
  let cumulativeDcMod = 0;

  // Iterate over all roll table ingredients
  rollTable.results.forEach(rollTableIngredient => {
    // Retrieve the custom name and dc modification value for the roll table ingredient
    let rollTableIngredientName = getProperty(rollTableIngredient, "flags.better-rolltables.brt-result-custom-name");
    let rollTableDcMod = getProperty(rollTableIngredient, "flags.better-rolltables.brt-dc-value");

    // Iterate over all input ingredients to check for matches with the roll table
    Object.values(recipeData.input).forEach(input => {
      let inputIngredient = Object.values(input).find(i => i !== null && i.name === rollTableIngredientName);
      if (inputIngredient && rollTableDcMod) {
        // If the input ingredient matches the roll table ingredient name, add the dc modification
        cumulativeDcMod += rollTableDcMod;
      }
    });
  });

  // Apply the cumulative dc modifications to all checks in the tests
  if (cumulativeDcMod > 0) {
    Object.keys(recipeData.tests.ands).forEach(andKey => {
      let andClause = recipeData.tests.ands[andKey];
      Object.keys(andClause.ors).forEach(orKey => {
        let orClause = andClause.ors[orKey];
        // Increase the check by the cumulative dc modification
        orClause.check += cumulativeDcMod;
      });
    });
  }

  console.log('All checks have been modified based on input ingredients.');
} else {
  console.error('recipeData, recipeData.tests, or recipeData.input is undefined or null');
}`

> There is official no such hook :-) especially no processed Hook.
> 
> Does it also have to do with tags ? I have the feeling you all try to do exaclty the same at the exact same time, its amazing.
> 
> So what i could provide and might become official is a hook?/setting to register a macro that will run prior to the macro execution time.
> 
> So this can then basically run globally for all recipes which makes it mostly useless... -> so probably it comes with some recipe filtering where this macro is available at.
> 
> I will think about it.
> 
> BUT still if you want this for itemTagger this alone will not help. Read here: #103

**Comment by AngryBeaver** [comment]
I figured filtering can be done on the hook itself. So keep it simple stupid here is your hook: 3.4.4

https://github.com/AngryBeaver/beavers-crafting/tree/v3.4.4?tab=readme-ov-file#beavers-craftingstart
