### ISSUE TITLE
[Feature Request] Enabling anyOf on the required fields

### ISSUE THREAD

**Issue by p4535992** [AngryBeaver/beavers-crafting#116]
Add for each component a checkbox to set the component as consumable or not, 

Because of different use cases it would save me a lot of time to have the ability to set on the recipe which component to consume or not consume.

In my specific case I have several anyOf that I don't want to consume, but I can't put them in the "required" panel (and I don't know if this is correct from a logic point of view), a simple check box to indicate which component not to consume, would be the easiest solution in my opinion.

**Comment by AngryBeaver** [comment]
If they are never consumed they would logically belong to the required section, as they are only required in the process not consumed.
So i would translate your request in enabling anyOf on required fields.
I can think about that.

If you mean to individually set consume on failed check. Then this would be checkboxes as mentioned above. 
My thought about that, space is tight their and not happy as this will probably polute datastructre there. 
Also not sure how to make the ui understandable nice especially as the checkboxes then need only appear when a test is given. 
This will probably not come.

**Comment by p4535992** [comment]
_So i would translate your request in enabling anyOf on required fields._

That would be the perfect solution, it's just that it seemed more onerous on your side as a development, so I had thought a simple flag on the components, but do as it comes back best to you

**Comment by AngryBeaver** [comment]
should be possible in v3.5.0
