### ISSUE TITLE
Pf1e Successful  Rolls show up green, then immediately turn red and "fail". 

### ISSUE THREAD

**Issue by Belgaron** [AngryBeaver/beavers-crafting#121]
![image](https://github.com/AngryBeaver/beavers-crafting/assets/45583090/83ff3b0c-6781-453f-b882-4f649d27f978)

It's even set up to fail after 2 failed rolls. But I roll 1 success and after a quick vision of the green success bar, it turns red and the crafting is failed. 

Very cool module. Hope it starts working for me soon.

**Comment by Belgaron** [comment]
I think its because the result is supposed to be a "scroll". I'll add it to a compendium and see if that works.

**Comment by Belgaron** [comment]
It works... I have to make an entire new compendium for scrolls =[.

Still a great module though

**Comment by AngryBeaver** [comment]
well fine that it works now for you. I still can not track what had been a problem you left too few clues.

Usually you do not need to have your results or ingredients come from compendiums but it is recommended as those items then are more stable while items imported into your world can be more easly be deleted or manipulated afterwards.

**Comment by AngryBeaver** [comment]
A recipe stores the link to the item not the item itself so when you delte an imported item your recipe will fail.

**Comment by Belgaron** [comment]
The scrolls in pf1 are "generated". There is no item sitting around called
"scroll of magic spell".

This didn't compute in my brain for the 30 minutes I was testing. Only
after I posted on here did it dawn on me.

100% user error. Module is perfect.

Tho I found it humorous that you named the list of recipes "compendium" yet
you cannot store them in a compendium.  :)
