### ISSUE TITLE
In CyberpunkRED system there's no option to rename recipe after creation

### ISSUE THREAD

**Issue by KpyrJIbIu** [AngryBeaver/beavers-crafting#122]
As it said in topic, after you create recipe item, name field is inactive, and there's no option to rename it.

**Comment by AngryBeaver** [comment]
uh allright i thgought you can edit the item name in the header as usually in other systems. I will make it like that.

**Comment by AngryBeaver** [comment]
try bsa-cyberpunkt-red-core 1.0.2. (editable header)
