### ISSUE TITLE
In CyberpunkRED system pinning recipe item in inventory is permanent.

### ISSUE THREAD

**Issue by KpyrJIbIu** [AngryBeaver/beavers-crafting#123]
In CyberpunkRED system there's option in character sheet to "pin" items, so they will appear even if you collapse a category in inventory. If you pin recipe item, you cannot unpin it.

**Comment by AngryBeaver** [comment]
i just tested it and it let me pin and unpin a recipe. The system should even not know that there is a recipe for the system it is a normal gear item. The recipe is nested into a gear item when you open it i just switch out the gear item sheet and show a recipe item sheet.
When you have problems maybe you have some console errors you may show me but typically this should not be a bug of my module.

**Comment by KpyrJIbIu** [comment]
Strange, tested it again, and it works fine. I think issue can be closed, if it occurs again, I'll record it and look for errors in console.
