### ISSUE TITLE
Inquiry: New 3.0 Foundry 5e Character Sheet

### ISSUE THREAD

**Issue by OnegoodgreekDM** [AngryBeaver/beavers-crafting#126]
Hi there! Wanted to update to the new character sheet but wanted to check if your module is compatible. I have a bunch of games coming up and your crafting mod is probably the players most favorite and important mod we use outside of normal dice rolls! Thanks again for all the hard work!

**Comment by AngryBeaver** [comment]
The bsa-dnd5e has already a 3.0 detection in it and when you run on 3.0 it should work with the ne charactersheet.
