### ISSUE TITLE
Cyberpunk Red - Test not Recognizing Skill Ranks

### ISSUE THREAD

**Issue by Unworthypilot** [AngryBeaver/beavers-crafting#127]
when running the tests for recipes, they are not recognizing skill ranks or role ranks that might contribute to crafting like the Fabrication Expertise for Techs. Everything must be entered manually except the STAT itself

**Comment by AngryBeaver** [comment]
bsa-cyberpunk-red-core v1.0.3 should fix this.

**Comment by Unworthypilot** [comment]
just updated to 1.03, it works now, thank you
