### ISSUE TITLE
[Feature Request] API for generating recipes from scripts

### ISSUE THREAD

**Issue by mnoreke** [AngryBeaver/beavers-crafting#13]
I have a lot of recipes to generate, and having access to an API would cut that time down by 90% or more as my data is in Excel and can be converted to a script much faster than using the UI.

Any chance in getting the relevant methods exposed? Or at least a quick writeup on what the module expects as data for it to work so I don't mess it up?

**Comment by AngryBeaver** [comment]
First of i doubt that this will work. While yes with the latest version i have weakend the reference,but you still need the correct valid uuid for at least the result items. 

Second my module do not cover the part of generating a new item, but when you find an endpoint from vtt to do that it might become possible from there to script a Recipe. 

Third yes this endpoint is not yet publically available but I can do so if wanted at my next weekend.

What would it look like:
First you have to set the type of your item to recipe as the system (dnd5e) dictates what types are avaiable i cheat here. Your Item must be of type="loot" and of ! source="recipe" !

Then basically i would enable you to reach this class:
https://github.com/AngryBeaver/beavers-crafting/blob/main/src/Recipe.ts.
There you can create a recipe class via Recipe.from(item)<- as said that is needed. 

Then you have methods recipe.addAttendants(entity, uuid, type), recipe.addResults(entity, uuid, type) and so on !and finally a recipe.update() which will update your changes back to the storage.

-> "entity" is that where your xml would have needed real worl uuid. e.g. you can use the result of  async fromUuid(uuid) which is delivered from vtt.
-> for non referenceable items (weakened reference) your entity still need to be an object of type ComponentData:
interface ComponentData {
    id:string;
    uuid:string;
    type:string;
    name:string;
    img:string;
    quantity:number;
    itemType?: string;
}
where you can choose to have id and uuid as invalid strings.

->type is the classType not the itemType so typically it is "Item" or "RandomTable".

but honestly i dont think you can script it and create working recipes your xml data would need to have correct uuids.

**Comment by AngryBeaver** [comment]
If you want to create raw data of an item and then somehow import them (compendium ?) then your data needs ofc to implement the interface of item5e (dnd5e) with type = loot and source = recipe.

and then add the custom flag beavers-crafting:
![image](https://user-images.githubusercontent.com/10677192/206551452-7604e20c-e3ee-462b-9f06-567d73f8e3e9.png)

The data strucur stored follows the RecipeData type:
https://github.com/AngryBeaver/beavers-crafting/blob/main/src/types.ts
You also find all other types in this link.

**Comment by AngryBeaver** [comment]
game["beavers-crafting].Recipe is now public available also i hope the interfaces are more stable with v1.0.0.
