### ISSUE TITLE
Mismatch between manifest and recommended package `id`s

### ISSUE THREAD

**Issue by rikmarais** [AngryBeaver/beavers-crafting#130]
Minor issue, but the package `id`s for some of the `relationship.recommends` system adaptations are not correct in the manifests. They differ from the actual `id` field in the system adaptation module.

In https://github.com/AngryBeaver/beavers-crafting/blob/main/module.json
![image](https://github.com/AngryBeaver/beavers-crafting/assets/34374883/32d64dee-6683-42ef-bccb-78184440f473)
```
		...
        {
          "id": "bsa-d35e",  <-- should be "bsa-D35E"
          "type": "module",
          "manifest": "https://github.com/AngryBeaver/bsa-d35e/releases/latest/download/module.json"
        },
        ...
```

In https://github.com/AngryBeaver/beavers-system-interface/blob/main/module.json
![image](https://github.com/AngryBeaver/beavers-crafting/assets/34374883/96b4a9fb-065b-44e3-887f-a1c33347dce7)
```
		...
        {
          "id": "bsa-dnd4", <-- should be "bsa-dnd4e"
          "type": "module",
          "manifest": "https://github.com/AngryBeaver/bsa-dnd4e/releases/latest/download/module.json"
        },
        ...
```

**Comment by AngryBeaver** [comment]
nice catch !

**Comment by AngryBeaver** [comment]
beavers-crafting will have to wait a bit for some additional fixes.
system-interface is fixed
https://github.com/AngryBeaver/beavers-system-interface/releases/tag/v2.1.10

**Comment by AngryBeaver** [comment]
fixed also in beavers-crafting now. Thx for the report.
