### ISSUE TITLE
Unable to activate module

### ISSUE THREAD

**Issue by CyantoIogy** [AngryBeaver/beavers-crafting#131]
When trying to activate the module in A5E or DND5E the checkbox is greyed out and I get a popup that says:

"Cannot be enabled due to issues in required dependencies"

When I installed it from Foundry, there was no popup for any dependency.

**Comment by AngryBeaver** [comment]
well this should not happen:
![image](https://github.com/AngryBeaver/beavers-crafting/assets/10677192/62383b7d-2ba4-40b3-ac9a-3691b327c574)
you would at least need to enable beavers-system-interface and a bsa-x module of your system.
As you can see in picture crafting module should recommend to download all those modules when installing it.

**Comment by CyantoIogy** [comment]
OK. I have the A5E adaptation, but I didn't have the other module. Installed that, and it did the trick. 

Thank you.
