### ISSUE TITLE
There is no recipe in creating an item

### ISSUE THREAD

**Issue by Jozhik2** [AngryBeaver/beavers-crafting#132]
There is no recipe for creating a new item. 
![brALECcSvZU](https://github.com/AngryBeaver/beavers-crafting/assets/165161842/56d0026e-8e18-44e1-968f-96977aef9bb1)

Try different names in the title of item cration dialog. The result does not change.
![_4zZqpRITxY](https://github.com/AngryBeaver/beavers-crafting/assets/165161842/7f3855d4-cadc-4b45-9525-73255438f079)

**Comment by AngryCrafter** [comment]
Did you figure this out?

**Comment by AngryBeaver** [comment]
you closed it i thought you found it out already ?
By the pictures i assume you are using v11 and dnd5 v3x.
I just tested it and yes sadly the v3 is visualizing a diffrent title here then internally the window will need to fix this:
for now when you use the engl language you can still use the old title is should be:
````
Create New Item
````

![image](https://github.com/AngryBeaver/beavers-crafting/assets/10677192/2d6050f9-0a22-4c18-ae3c-1745b62ed9fc)
