### ISSUE TITLE
Crafting Panel wont appear [5e]

### ISSUE THREAD

**Issue by Mariora008** [AngryBeaver/beavers-crafting#136]
So in one of my pcs characther sheet won't appear the option to craft, this is the second time it happens (the first one i fixed it by recreating the character from scratch) the problem it happened again with the "same" character, the only thing special this character has that any other have is multicass i don't know if this is any useful. Maybe useful is the fact that the issue won't fix even if I change de id or if I export and import the character in another actor, so i thing the module may be messing with the metadata of the actor.

Here is an image so you can see it won't appear in an specific character sheet but it does in others
<img width="157" alt="bcmfvtt" src="https://github.com/AngryBeaver/beavers-crafting/assets/84105503/add3ef49-131e-4fb1-9e53-ae5e0d4ea05d">

**Comment by AngryBeaver** [comment]
well hard to detect why from this side of the screen only.

hit f12 this will open up a console.
I am quite sure there will be some errors shown there else it would have worked.
The error will mostlikely hint to a problem.

**Comment by AngryBeaver** [comment]
something like this only with an error that has to do with your problem:
![image](https://github.com/AngryBeaver/beavers-crafting/assets/10677192/2a647121-d94f-4df8-89d0-2831a305a3b6)
