### ISSUE TITLE
"cannot be enabled due to issues in required dependencies"

### ISSUE THREAD

**Issue by AlexanderMee** [AngryBeaver/beavers-crafting#138]
I can't activate the module:

Foundry ver 12

dnd5e ver 3.2

**Comment by AngryBeaver** [comment]
beavers-crafting requires at least beavers-system-interface and the adaption for your system beavers-system-adaption in your case its bsa-dnd5e i guess.
If you miss some of the modules try deinstall and install again of beavers-crafting.
Usually when installing those modules foundry gives you a popup with additional modules you require or that are optional. there you can select all bsa-x modules you need. you may also found em here: 
https://github.com/AngryBeaver/beavers-system-interface/wiki/BSA-x-links

**Comment by AlexanderMee** [comment]
Hello thanks for your quick response.

The issue I was running into was there is a lag between "module successfully installed" and the dependencies pop-up. I was clicking away from the install screen too fast. Thank you for your help.
