### ISSUE TITLE
[Feature Request] Spell consumption

### ISSUE THREAD

**Issue by Janner3D** [AngryBeaver/beavers-crafting#14]
Would it be possible to allow spells to be part of the recipe? 

For example: 
An item has a spell as part of the recipe. When crafted, it referenced any spells or spell scrolls with the same name on the character sheet. As part of the crafting process, the recipe could prompt the crafter to use the spell or scroll as if rolling them, thus expanding the scroll, or spell slot.

**Comment by AngryBeaver** [comment]
Well probably not as you like to see it but it will become possible.

Last weekend i already started implementing the upcomming macro addition. 
You can code what ever you want into it. The macro will recive the actor and a recipeResult. This macro gets executed then before updating the actor according to the result and sending the chat message wich will also be included in the recipeResult.

With this addition many of my requests for this module gets possible while i do not need to make my code increasingly complex with every possible combination of things that are needed :-)

So yes it will become possible but without much ui support and you need to script it.

**Comment by Janner3D** [comment]
> So yes it will become possible but without much ui support and you need to script it.

I'm a fairly novice scripter, so I'll probably struggle with this 😅

**Comment by AngryBeaver** [comment]
Now possible with macros although this is not simple to implement if you want it fullout correctly. A simple solution can be found:
[This is no simple task to give you an idea for simple spell consumption you can ](https://github.com/AngryBeaver/beavers-crafting/blob/main/macros.md#simple-spell-consumption)
