### ISSUE TITLE
[Bug][5e] Recipe is no longer appearing in list

### ISSUE THREAD

**Issue by Thomas9666** [AngryBeaver/beavers-crafting#141]
Can't remember when I last made a recipe but the option has now disappeared when clicking on "Create Item". 
![image](https://github.com/AngryBeaver/beavers-crafting/assets/68351248/5da84604-314c-47f2-b9f8-63bedf17615e)

Recipes still function, one player had an active craft on his sheet and progressed it, and "new" recipes can be made in a workaround through duplicating an existing recipe and altering it. 

Wasn't sure if it was my UI module acting up, tried disabling it and still cannot create a new recipe item through the standard method

**Comment by AngryBeaver** [comment]
It might happen when you change the language of your foundry. Have you tried the troubleshoot guide:
https://github.com/AngryBeaver/beavers-crafting?tab=readme-ov-file#solution
