### ISSUE TITLE
Ingredients not being consumed on completion

### ISSUE THREAD

**Issue by Darjette** [AngryBeaver/beavers-crafting#142]
When a crafting task has been completed, the required ingredients to craft it are not being consumed. They remain in the inventory until my players manually delete them. I have tried testing this with various settings turned on and off and the issue seems to persist.

**Comment by AngryBeaver** [comment]
just tested with foundry v12 , D&D3.2.1
Works as expected so i asume it is not something general.

Troubleshooting:
When you look at your recipes make sure that the items you want to consume is in the cost section not the required section. Required items are per designt not consumed just required:
![image](https://github.com/AngryBeaver/beavers-crafting/assets/10677192/56de8e04-14f2-4659-9be1-b79c30c1d67c)

If that is all fine then i would need more insight into your setting:
plz tell me what foundry version and what system you are using.
Also when you reproduce the bug hit f12 open up a console and watch out for errors in there maybe it conflicts somehow with some module or configurations.

![image](https://github.com/AngryBeaver/beavers-crafting/assets/10677192/b0910d38-1064-45b0-b8c8-260bc772251e)

**Comment by Darjette** [comment]
That seems to have been it. I assumed that 'Cost' was strictly for monetary investment. My mistake! Thank you.
