### ISSUE TITLE
[Feature Request] Document Link output

### ISSUE THREAD

**Issue by JackaldaJester** [AngryBeaver/beavers-crafting#143]
Hello,

Is there a way to display the result as a document link in the chat box versus (or maybe in addition to) just seeing the results of the roll?

For example, I have a player that's cooking a meal. If they succeed, then a document link pops up in the chat box and the other players could drag the meal item into their inventory as well.

**Comment by AngryBeaver** [comment]
I will think about it.

I am unsure about creating one item and duplicating it as often as wanted or do you need to create the amount you want to produce. -> how then to prevent takeing more then only this amount.
The created item exists only in the player inventar possible a technical complication for other players
Are there maybe other modules that may do this. e.g. item-piles ? a merchant type user that other can interact with and take the item from. etc.

**Comment by JackaldaJester** [comment]
There is definitely a number of ways to get around what I'm trying to do, but I'm trying to do it the most convenient way for my players.

In the PF2e system for Foundry, when a spellcaster casts a buff the buff will pop up in the chat box. Anyone who is eligible to receive the buff can drag the buff document link from the chat box and onto their character sheet, and then it becomes an active effect. 

I understand there might be a concern for players might taking more than they should, but for my own personal game with friends I am not concerned with that. I don't know if there is a way to mitigate that.

Thank you for reading though!

**Comment by AngryBeaver** [comment]
I am between vaccations so this is the simplest solution also hadn't much time to test it:
Did test it for dnd5e + foundry v11.315 and dnd5e + foundry v12.232. So at least compatible for 11 and 12 not sure about other systems but it should work.

Copy via drag and drop comes at a price see Limitations at:
https://github.com/AngryBeaver/beavers-crafting?tab=readme-ov-file#draggable-chat-result

the feature is disabled per default.
released in v3.6.0

**Comment by JackaldaJester** [comment]
I haven't tested it out fully yet, but so far so good. Thank you!
