### ISSUE TITLE
Tool Config Empty on update

### ISSUE THREAD

**Issue by Nightpresider** [AngryBeaver/beavers-crafting#144]
Just as the title says, after updating the module my tool config (which for me has about 50 tools) empties. 
I haven't been able to catch it in action as i tend to hit [update all] on the modules list.

**Comment by AngryBeaver** [comment]
if you speak abnout tools i asume the tool config which is available only in dnd5e.
![image](https://github.com/user-attachments/assets/6b261c57-959c-4025-a7a1-3fa61ff71c8f)

this does work for me for latest beavers-crafting 3.6.0 and latest dnd5 -> 3.3.1.
Maybe some other module is interfering for you ?
you may hit f12 and search for some error logs.

**Comment by AngryBeaver** [comment]
or you added a custom tool that is now deleted... i vage remember someone having issues with that.
So it can not render the list anymore as it is now incomplete. if thats the case give me the error log i may be able to build the tool config more robust to handle such cases.

**Comment by AngryBeaver** [comment]
can't help when i can not reproduce it.
