### ISSUE TITLE
[Feature Request] Add pt-BR Language.

### ISSUE THREAD

**Issue by Andersants** [AngryBeaver/beavers-crafting#148]
Hi. This is a great module, congratulations.

Here is the translation into Brazilian Portuguese.

[pt-BR.json](https://github.com/user-attachments/files/16918957/pt-BR.json)

**Comment by AngryBeaver** [comment]
wow, that is nice. thx. 
I will reference you in the readme.
"translated to Brazilian Portuguese by Andersants"
