### ISSUE TITLE
[Bug][5e] Recipe is no longer appearing in list

### ISSUE THREAD

**Issue by toldizzle** [AngryBeaver/beavers-crafting#149]
This looks hard to reproduce since I have only been able to do it on non new worls...

Foundry 12.331
DnD 5e 3.3.1
All of your modules for Dnd5e udated (since today), I saw that you changed Adaption to Adaptation in latests commits (might be it?)

![image](https://github.com/user-attachments/assets/cab0bf0c-6e8c-4889-92c4-1f66a3711b66)
![image](https://github.com/user-attachments/assets/b91a3759-e580-4962-80c3-d2ca66580527)
![image](https://github.com/user-attachments/assets/183950aa-8eb8-494a-9d81-8cdb6774b42a)
![image](https://github.com/user-attachments/assets/22ec280d-87fa-4757-92f0-c809719d70c0)

**Comment by toldizzle** [comment]
I forgot to add that i normally play in french.

**Comment by AngryBeaver** [comment]
Item migration is an initialisation process to migrate data structure from beavers-crafting 3.x to 4.x.

In this process the Tests where removed from beavers-crafting to system depending files. E.g. beavers-System Adaption dnd5e.
The PopUp tells you that the migration had found a problem. 

It tries to migrate recipes it has found with tool Tests e.g. such that needed you to roll a tool to the new ToolTest.
beavers-system-adaption dnd5e will usually register this ToolTest and then it would be available.

The migration error tells me that the ToolTest is not a registered Test.
Maybe I need to check the timeing of my migration script from beavers-crafting to my bsa-dnd5e startUp it might be that for you beavers-crafting got loaded first. This is something i will check and fix.

On the other side some code of my bsa-x implementation might have also thrown a bug for any reason i do not know, on your side and this prevented the registration of the ToolTest. Can you check if you got any other errors when refreshing the page ?

**Comment by AngryBeaver** [comment]
4.0.5 released.

The migration process is now asynchronously and starts with a delay of 10 seconds.
If it breaks it will no longer break the crafting module overall.

If this does not help you then you probably do not have the racing condition issue i assumed you might have or you have a real slow server :-).

When you still get the error message then you probably have some other error that prevents bsa-x to load correctly, look out for them. If there is nothing else and it keeps throwing this error ping me maybe i can try and identify another possible problem.

**Comment by toldizzle** [comment]
Hmm, for some reason, all my receipe on the world where you migration was working changed Alchemist Tool to Carpenter Tool(first of the list) after updating to 4.0.5.

It did remove the error on other worlds, so data got migrated, but it reseted the tool test to (choose) instead of what was selected before the migration.

**Comment by AngryBeaver** [comment]
thx for your feedback.
tool migration fixed in v4.0.6 for those who not yet have migrated.
