### ISSUE TITLE
[Bug] [Pf1] Whenever I failed a skill check, craftin tab disappear

### ISSUE THREAD

**Issue by galateio** [AngryBeaver/beavers-crafting#150]
Whenever I failed a Skill Check trying to craft an item the Recipes tab of the PJ sheet disappear. 

![imagen](https://github.com/user-attachments/assets/28d0b974-b3e7-46c5-97c0-2a1d5b212cce)

Before
![imagen](https://github.com/user-attachments/assets/f0ac01af-4cda-4651-b140-7194567bc613)

After
![imagen](https://github.com/user-attachments/assets/b1eab9cc-1cab-426c-90d4-7f4831b489b2)

The recipe is:
![imagen](https://github.com/user-attachments/assets/6b09a529-43b9-497b-b2ff-f30358d0ac8d)

And the error in the console:
![imagen](https://github.com/user-attachments/assets/62660901-1a88-4d27-a2b2-c255f59cb6ab)

I'm still on FoundryV11

**Comment by AngryBeaver** [comment]
Thanks for your report and detailed pictures. I could reproduce this bug and can confirm that there are at least 3 bugs exaclty there :-).
1.) bug it currently always tries to return the money when the check failed also it should consume it.
2.) bug returning money is asynchron but it didn't wait for the method.
3.) is unknown yet 

i will need some time to dig up more.

**Comment by AngryBeaver** [comment]
fixed bsa-pf1 1.1.1 + beavers-crafting 4.0.7
