### ISSUE TITLE
[Feature Request] PF2e system compatibility

### ISSUE THREAD

**Issue by altair984** [AngryBeaver/beavers-crafting#16]
Hi, I was wondering if there was any possibility that your module could also work with the PF2e system. I love dnd5e and it is already an essential tool for my campaigns, but I also run PF2e campaigns and it would be very useful for me. Thank you very much!

**Comment by AngryBeaver** [comment]
Well probably possible but would need a lot refactoring.
1.) i depend on a dnd5e css style wich is probably anyway bad.
2.) i use some system specific variables. like currencies and quantity all of those needs to be refactored into a stub with multiple implementations for diffrent systems. (that would take some time)
3.) i have bundled example packs (component) into the module which use dnd5e dependencie

On top i personally have no gain in it as i do not host any pf2 campaign, just to be honest this will ofc have an impact on how possible this will become to get implemented.

so unlikely this will come soon.

but I will tell you this. 
I am currently working on creating more examples (potions) for my campaign and those anyway have a lot of dependencies to other 5e modules so i should probably split my potions out from the crafting module. leading to solving 3.
Then the next thing i am willing to do is to get away from dnd5e css as coupling here makes my module more fragile (dnd5e might change the css and will then break my module, i do not need this coupling) this will solve 1.

As for 2) This i will keep in mind as boyscout principle e.g. whenever i will work on code that is system specific i will refactore it to an interface with a dnd5 implementation. 

-> after some time this might lead to reducing the complexity for your request thus making it more plausible that i will start working on it.

**Comment by AngryBeaver** [comment]
now it should also run on pf2e

**Comment by altair984** [comment]
thanks so much :)
