### ISSUE TITLE
[Feature Request] Learn Recipie

### ISSUE THREAD

**Issue by gubacelar** [AngryBeaver/beavers-crafting#18]
The possibility to learn the recipie.
It's like a book where you can write your recipie. So first you need the recipe item, and the you "consume" it and the recipie goes to your "Know Recipies" tab.

The idea of this is something similar to [world of warcraft professions.](https://www.wow-professions.com/wotlk/alchemy-leveling-guide-wotlk-classic).

**Comment by AngryBeaver** [comment]
No sry, i do not like this idea for two reasons.
1.) you can do something similar already
2.) the actor data gets poluted and then you also need a system to manage aka cleanup known recipes.

as to 1)
As dm you can set any recipe to private access so no one sees the available recipes. 
It is already in your power to hand a recipe to your players.
When a player has a recipe in his inventar this recipe is in his knwon recipes.
This way you already can also manage knwon recipes just move the recipe item out of the actor.

What would change if i do it your way. The dm still needs to hand out recipes but then the user must also first click it to learn it.
so it is just one action more then before.

Also this data is intransparent e.g. if you have to recreate your actor for any reasons e.g. reimport it from dndbeyond there is no way of copying this knowledge over.

**Comment by AngryBeaver** [comment]
if you want your players to learn a recipe from a book. you can make a recipe looking like a book if they click on it the recipe gets executed if the result of the recipe is another recipe the actor "learned" that recipe from the book.

you can also make a check for that learning process. ;-)
