### ISSUE TITLE
[Enhancements] Not everything is good to throw away !

### ISSUE THREAD

**Issue by Steelskinz** [AngryBeaver/beavers-crafting#2]
Simple idea to not lose all of the items when failing a crafting check.

**Comment by AngryBeaver** [comment]
Nut sure i will think about it:

- It is mostlikly a breaking change as the old flag will vanish for several flags on the ingredients and currency. 
- Also checking or unchecking all like now has then increased complexity, or the uis complexity increase.
- Maybe when i invent crafting macros it is more simpler to lose or keep items via macro. ofc this renders this feature for advanced users only as not everyone can or is willing to write macors. I have to think about it.

**Comment by Steelskinz** [comment]
Aaah. Understood. Let's not ruin a good cake with extra things on it.  I think since Toolkit will be added, I don't need this that much. Thanks for your hardwork and again, that's a really great module !
