### ISSUE TITLE
[Bug] Ingredient non-detection

### ISSUE THREAD

**Issue by MasterCroissant** [AngryBeaver/beavers-crafting#21]
Been trying for 2 hours to understand the problem, so here is my analysis of this case so far:

1) Recipes from the module compendium are working just fine. Importing a recipe from the compendium with the required ingredients doesn't break the module and the craft can be made without any issue. 

2) Modifying a functioning recipe by changing the skill check or the gold amount required doesn't break the recipe.

3) Deleting an ingredient from the functioning recipe doesn't break the recipe.

4) Deleting an ingredient from the functioning recipe, and replacing it with the same ingredient directly from the module's compendium DOES break the recipe. The break in question prevent the module from detecting said item from the player's inventory, even though it is taken from the same source (i.e. the compendium)

5) Creating a recipe from any ingredient, even directly from the module's compendium or a custom item list break the recipe.

Conclusion: The break in question prevent the module from detecting an item in a character's inventory that is dropped from any source in a crafting recipe. I have tried everything, as to making different types of item (loot, consumable, weapon, etc.), and the same thing occurs. Unfortunately, I have zero experience in programming, so as far as this goes, I have no other idea what is going on...

**Comment by AngryBeaver** [comment]
yes thx for checking this and reporting. 
I haven't tested it and yes you are right it does not detect the itemType when dropping in from compendium and thus it can not detect equal as this checks for itemType.

I am currently confused how i managed that before but will figure it out :-)

**Comment by AngryBeaver** [comment]
should be fixed with 2.3.1. 

has another sideeffect AnyOf items now also have a detected type. -> but i can not see that this has any negative impact.

**Comment by MasterCroissant** [comment]
Thank you so much!!

**Comment by AngryBeaver** [comment]
beavers-system-interface 1.0.7 should now fix this.
