### ISSUE TITLE
Adding Proficiency modifier

### ISSUE THREAD

**Issue by fredrlw** [AngryBeaver/beavers-crafting#23]
Hi, I wondered if it was a possibility to add proficiency to the roll when using attendants, atleast when the PC is proficient with the tool.

Ex. using Herbalism kit as attendant, skill = Intelligence, DC =12
right now, you just need to have a herbalism kit, no bonus for being proficient with it

Prior, I could manualy add bonus to the crafting roll, but now I don't seem to get that option anymore

Anyhow, Really loves the module! :)

**Comment by AngryBeaver** [comment]
your request is two folded the one is rolling with tools. This is ... complicated as of design reasons and i probably wont fix it fast, sry.
The request is similar to an older one  and i will use the existing one to keep track of this problem. https://github.com/AngryBeaver/beavers-crafting/issues/15

The second problem you encounter that you do not get a popup anymore for roll options, probably you refer here to dnd5e i think i have encountered this too but not sure. So i will use this ticket to fix the second part.

Prio for this: i consider it a complicated bug so high prio but needs time getting to it so probably i will try this weekend.

**Comment by AngryBeaver** [comment]
ok i checked it in dnd5e and the popUP dialog appears for abilities as well as skills.
![image](https://user-images.githubusercontent.com/10677192/218077768-6b12308a-2045-4859-a3fb-29e1feeba06e.png)
here you should be able to add boni.

The same is true for pf2e:
![image](https://user-images.githubusercontent.com/10677192/218078103-9062e71e-87cd-4336-b6b3-e2a5532558f6.png)


If you use any automation roll modules they ofc might change the behaviour.  e.g. midi-qol in full automation has a checkbox to automate ablities this then leads to abilites rolled on actor wont pop up that window and this also then won't popUp the window when you craft. 

Other roll modules might do it completlty diffrently and maybe only block it in my crafting that i do not know.
Can you check if it is another module and if it is if you have done some automation setups in those modules that prevent showing the popUp window.

e.g this checked in midi-qol prevent the popUp:
![image](https://user-images.githubusercontent.com/10677192/218077684-7d157fe0-4f6e-4367-bcb2-c65a5813678a.png)

**Comment by AngryBeaver** [comment]
you now can select tools as test option. Attendants will still be only attendants without roll benefit but you now have a possibility to create recipe that can use tools.
