### ISSUE TITLE
[Feature Request] 3.5SDR system compatibility

### ISSUE THREAD

**Issue by valhallatoys** [AngryBeaver/beavers-crafting#26]
I've been looking for something like this for a long time, it's really incredible but I wonder if it would be possible to have compatibility with the 3.5SDR system (D&D 3.5)?

**Comment by AngryBeaver** [comment]
yes, i think it would run with 3.5 dnd, but :-)

well in the end someone has to write a tiny adaption layer and this one should be best someone that is familiar to the system.
I developed this module in a way others might write their system adaption independently of me.

All that "someone" has to do is fork one of my two example repo: https://github.com/AngryBeaver/bsa-dnd5e
and implement a couple of methods the file is pretty small the most implementations are trival but need the knowledge of that system.

most complex is the currency methods, but if you have a system like pf2e that uses items as currency you can remove those there is a default implementation for those systems.

````
export class Dnd5e implements SystemApi {

    get version() {
        return 1;
    }

    get id() {
        return "dnd5e";
    }

    async actorRollSkill(actor, skillId):Promise<any> {
        return await actor.rollSkill(skillId);
    }

    async actorRollAbility(actor, abilityId): Promise<any> {
        return await actor.rollAbilityTest(abilityId);
    }

    actorCurrenciesGet(actor):Currencies {
        return actor["system"].currency;
    }

    async actorCurrenciesAdd(actor, currencies: Currencies): Promise<void> {
        const actorCurrencies = this.actorCurrenciesGet(actor);
        const addValue = beaversSystemInterface.currenciesToLowestValue(currencies);
        const actorValue = beaversSystemInterface.currenciesToLowestValue(actorCurrencies);
        const result = actorValue + addValue;
        if (result < 0) {
            throw new Error("negative money");
        }
        const resultCurrencies = beaversSystemInterface.currencyToCurrencies(result);
        await actor.update({system: {currency: resultCurrencies}});
    }

    actorSheetAddTab(sheet, html, actor, tabData:{ id: string, label: string, html: string }, tabBody:string): void {
        const tabs = $(html).find('.tabs[data-group="primary"]');
        const tabItem = $('<a class="item" data-tab="' + tabData.id + '">' + tabData.label + '</a>');
        tabs.append(tabItem);
        const body = $(html).find(".sheet-body");
        const tabContent = $('<div class="tab" data-group="primary" data-tab="' + tabData.id + '"></div>');
        body.append(tabContent);
        tabContent.append(tabBody);
    }

    get configSkills(): SkillConfig[] {
        return Object.entries(game["dnd5e"].config.skills)
            .map(skills => {
                // @ts-ignore
                return {id: skills[0], label: skills[1].label as string};
            })
    }

    get configAbilities(): AbilityConfig[] {
        return Object.entries(game["dnd5e"].config.abilities).map(ab => {
            return {id: ab[0], label: ab[1] as string};
        });
    }

    get configCurrencies(): CurrencyConfig[] {
        return [
            {
                id: "pp",
                factor: 1000,
                label: game["dnd5e"].config.currencies.pp.label
            },
            {
                id: "gp",
                factor: 100,
                label: game["dnd5e"].config.currencies.gp.label
            },
            {
                id: "ep",
                factor: 50,
                label: game["dnd5e"].config.currencies.ep.label
            },
            {
                id: "sp",
                factor: 10,
                label: game["dnd5e"].config.currencies.sp.label
            },
            {
                id: "cp",
                factor: 1,
                label: game["dnd5e"].config.currencies.cp.label
            }
        ]
    }

    get configCanRollAbility():boolean {
        return true;
    }
    get configLootItemType(): string {
        return "loot";
    }

    get itemPriceAttribute(): string {
        return "system.price";
    }

    get itemQuantityAttribute(): string {
        return "system.quantity";
    }

}
````
I fear this is not the answer you wanted :-) but at least there is a simple path to make it possible.

**Comment by valhallatoys** [comment]
I have no idea about programming, so I'll have to wait for someone to upload the compatibility module for my game system. Thanks for your prompt response.

**Comment by AngryBeaver** [comment]
also here i won't make any promises but i keep this ticket open maybe i will do it at somepoint if no one has done it before.

**Comment by valhallatoys** [comment]
I apreciate it

**Comment by AngryBeaver** [comment]
arh not easy the system is not ready for what my module needs or i do not understand how i suppose to do it. However got something running after patching the system. I left the author a merge request:
https://gitlab.com/dragonshorn/D35E/-/merge_requests/907
If this gets merged i can create the adaption layer.

**Comment by elizeuangelo** [comment]
Im working on a D35E compatibility module and its almost completely done, but im running on the issue that the Item Sheet is not well designed for the system.

Would be possible to create a Hook so I can change the rendered template wich is appended to `.beavers-crafting.recipe`?

**Comment by AngryBeaver** [comment]
oh nice i wasn't able to get the roll result back for the d35e system.

The item sheet for recipes is completly attached with onclick methods linking into the recipe. e.g. the drop area or the delete icons etc. I do not think that it is possible that you can use a new template that then would work with the recipe backend.

Also note the system adaption layer is not designed to make changes to a specifc module e.g. beavers-crafting. the system-adaption layer should not know anything about modules that make use of it so i wont implement something that is for one specific module. 

hm ... well you can ofc write a module that is implementing the system adaption layer and additional adaption for beavers-crafting module.
my currently [approach]( https://github.com/AngryBeaver/bsa-D35E) is blocked for i do not know how to get the roll result back from the d35e system and it seemed to me that i would need to patch the system like i [did ](https://github.com/AngryBeaver/beavers-crafting/issues/26#issuecomment-1514168262) but maybe there are other aproaches ?

**Comment by AngryBeaver** [comment]
If it is about the styling maybe i can get back to create more css over inline styleing so you can override the css definitions.

But this aproach mitght get instable as the css has no public api for me so if i change the ui and move elements around it may break with other css stylings i am not aware of.

**Comment by AngryBeaver** [comment]
maybe you need only this part that i apparently had written that overrides the default saveMCE method that somehow seemd to have been needed:
        [app.saveMCEContent = async function (data = null) {

        }](https://github.com/AngryBeaver/bsa-D35E/blob/62237a07642627db11db2b1b255f0fa9c53d900d/src/D35E.ts#L41)

**Comment by AngryBeaver** [comment]
I just realize that basically [this](https://github.com/AngryBeaver/beavers-system-interface/wiki/Beaver's-System-Interface#itemsheetreplacecontent) is kinda the place you asked for here you may intercept the template element e.g. for beavers-crafting module the originial recipe template.

**Comment by elizeuangelo** [comment]
Im gonna make a pull request to D35E system tomorrow wich will solve lots of issues

**Comment by elizeuangelo** [comment]
> https://gitlab.com/dragonshorn/D35E/-/merge_requests/911
https://github.com/elizeuangelo/foundryvtt-module-bsa-D35E

I've made roll results return results, lets wait and see if the system accepts the PR.
Now the module seems rudimentary working despite some CSS and sheet bugs:
- the system dont use `_tabs` wich bugs the ActorSheet because of Beavers Crafting listeners
- Item sheet is ugly and bugged as well, ideally beavers Description tab should be removed (alongside the prosemirror) and Main and Advanced tabs should be secundary tabs following D35Es design

Lets think more about this once and if the system approves the PR

**Comment by AngryBeaver** [comment]
Well i also had a [pr](https://gitlab.com/dragonshorn/D35E/-/merge_requests/907) for the return of roll results but he hasn't merged that, now it is no longer compatible to main branch i hope yours get attention :-).

**Comment by AngryBeaver** [comment]
finally looked into it and the pr seemed closed and it does work now:

https://github.com/AngryBeaver/bsa-D35E
fixed the _tabs bug 

the style on items could be better but its not that bad.

AnyOf is rendering but the test + drag/drop seems not to work in recipes however it gets executed perfectly.
closed for now was open long enough  and this adaption layer works at least good enough for now :-)

**Comment by elizeuangelo** [comment]
Thank you very much Beaver!

**Comment by AngryBeaver** [comment]
bsa-D35E 1.0.1 fix skills
- tested only abilities and missed that skills do not return a Roll array.
