### ISSUE TITLE
[Feature Request] Choice of one of two ingredients

### ISSUE THREAD

**Issue by IceWindy** [AngryBeaver/beavers-crafting#29]
It would be nice to have the ability to select one of two crafting items, for example: we have a sword craft, and the players have, say, steel, iron, and bronze ingots, the sword made from them should be the same, and you need the player to be able to choose, what material of these three will he make the sword.
Maybe it will be useful only for me, because I have a group of engineers who constantly make something from iron, steel, or armored alloys, often it does not matter what they make, say, nuts and bolts, and create three times as many recipes for me it would be inconvenient.
Another option is priority for use with AnyOf maybe :)

**Comment by AngryBeaver** [comment]
Not quite sure what it is you want exactly.
If you want to create a sword from one of three items steel item and bronze and you do not want to create three diffrent recipes as all create the same sword. Then you could go for anyOfs, the player can drag and drop the ingredient they want on the recipe before they craft to choose which ingredient they want.
[anyOf](https://github.com/AngryBeaver/beavers-crafting#anyof)

not supported are ingredients with anyOf as result you can however drop a rollTable in the results.

but when i look at your title this should be working with anyOf. 
Just update to the latest version 2.3.4 i had some issues with anyOf latly.
