### ISSUE TITLE
[Enhancements] Add a slider on recipes.

### ISSUE THREAD

**Issue by Steelskinz** [AngryBeaver/beavers-crafting#3]
When there's too much recipes available it seems to drive away the Craft button. Luckily you can resize the window, but it would be better if it didn't deform.
![image](https://user-images.githubusercontent.com/93941729/197316789-37ab8f55-80eb-4861-b02b-286f0cf126c8.png)

**Comment by AngryBeaver** [comment]
will be fixed in 0.4.1
