### ISSUE TITLE
[Feature Request] toggle crafting tab for NPCs?

### ISSUE THREAD

**Issue by ctbritt** [AngryBeaver/beavers-crafting#31]
Sorry if this is a basic question, but is there a way to toggle the crafting tab for NPCs? NPCs don't craft, so they don't need the tab... (at least they don't in my game world...)

**Comment by AngryBeaver** [comment]
currently not i haven't thought about this.
I think this needs some system dependent detection about what is a player actor.

i will kepp this as FeatureRequest

**Comment by AngryBeaver** [comment]
I just found a broken setting i once implemented. You can at least now 2.3.5 disable the "Recipes" header from all actors. 
While this does not effect the tab on the npcs this will at least cleanUp the titlebar. Especially with multiple modules i had problems to find a free space to drag the monster sheet or the close button has been pushed out of sight.

other then that this feature has not yet made it to the next 2.4.x so you need to be patient.

**Comment by AngryBeaver** [comment]
3.2.x included into the or feature release
