### ISSUE TITLE
[Feature Request]  SWADE Compatibility

### ISSUE THREAD

**Issue by anthonydeaver** [AngryBeaver/beavers-crafting#34]
Any chance of support for Savage Worlds, or guidance oh how to adapt?

I know I probably don't need it but my players asked so....

**Comment by AngryBeaver** [comment]
Well i think it should work but "someone" has to write  a tiny system adaption layer. see other answer.

https://github.com/AngryBeaver/beavers-crafting/issues/26#issuecomment-1421151264

I will keep this open here it might happen that i will at some point write the layer but it has super low prio as i currently have no clue about that system.

**Comment by AngryBeaver** [comment]
https://github.com/AngryBeaver/bsa-swade
