### ISSUE TITLE
[Enhancements] Let players know what they are trying to craft.

### ISSUE THREAD

**Issue by Steelskinz** [AngryBeaver/beavers-crafting#4]
We cannot click on items. In the materials part like the crafting result part. Players should know what they're trying to craft.

**Comment by AngryBeaver** [comment]
seems simple i will implement it next. Btw. I like that my player do not exaclty know what exactly it is they are crafting, so probably   i will implement it with settings.

**Comment by AngryBeaver** [comment]
fixed in 0.4.1
