### ISSUE TITLE
Deleting owned recepies

### ISSUE THREAD

**Issue by w1face** [AngryBeaver/beavers-crafting#40]
I can't find anywhere to delete recipes from a character.  I "dragged" one over, and have since changed it, but the old one still shows up in "owned".

**Comment by w1face** [comment]
Found them in "Loot"!

**Comment by AngryBeaver** [comment]
in v10 you can not really add additional item types so i fake one that is base on an item type on the system beavers-crafting is running on. For dnd this is loot. 

Also in v11 it reads as if it would now be possible to add custom types. 
However i will not soon change that as then i would drop the support for v10.

so yes you will find for most systems the recipes in the inventar of the user.
