### ISSUE TITLE
Ingredients with quantity of 0 can still be used by recipes.

### ISSUE THREAD

**Issue by SirGarhi** [AngryBeaver/beavers-crafting#41]
An item with a quantity of 0 can still be used in a recipe that requires a quantity of 1.

**Comment by AngryBeaver** [comment]
well yes did not consider items of quantity 0. I will look into it to fix it.

details:
when no quantity is given i default to 1. 
In javascript a zero can be detected as false. I probably did not do a correct type check here... rookie mistake.

**Comment by AngryBeaver** [comment]
should work now in 3.0.2 beavers-crafting and 2.0.0 beavers-system-interface
