### ISSUE TITLE
Ingredients not refunded on automatic failure due to missing attendant or ingredients

### ISSUE THREAD

**Issue by SirGarhi** [AngryBeaver/beavers-crafting#43]
If you try and craft a recipe without having the required attendant(s) or all the necessary ingredients, it still locks all of the ingredients you do have, then automatically fails.

The ingredients that were locked are not refunded, even if the recipe is set to not consume on a failure.

**Comment by AngryBeaver** [comment]
thx for reporting i will look into it.

**Comment by AngryBeaver** [comment]
should work now in 3.0.2 beavers-crafting and 2.0.0 beavers-system-interface
