### ISSUE TITLE
Recipes with a crafting cost cause all coins to be converted to the highest denomination.

### ISSUE THREAD

**Issue by SirGarhi** [AngryBeaver/beavers-crafting#44]
If a recipe has a crafting cost to it, all coin on the character sheet will get converted to the highest denomination (IE Platinum in DnD 5e) when the coin is locked by the recipe being added to the crafting tab.

This is... less than ideal for any games that actually track what type of coins you are carrying. It's also a problem if you have a recipe that you want to require a specific type of currency, like crafting Silver Bullets requiring 100 silver coins specifically, instead of 10 gold coins or 1 platinum.

**Comment by AngryBeaver** [comment]
yes that is also noted here: 
https://github.com/AngryBeaver/beavers-crafting#currency-reorder

I mean for most recipes money is meant as cost it is fine to exchange making the use of the recipe easier.
For recipes like the one you pointed out where the costs are well more like an ingredient there ofc you wanted exaclty that currency.
(In pathfinder money is an item and i think you could use them there also as an ingredient which would do what you want)

detail:
About exchange reordering: I use the most simple algorithm for exchanging. 
Consider this: "Something costs 12 gold and you have 1pp 1ep 1gp 100sp and 200cp". What would be the best automated exchange of that ? And now think about an algorithm implementation for this :-).

I will think about a solution for dnd, but it wont be of high prio to me.

**Comment by SirGarhi** [comment]
Possibly make it a module setting?

I'd honestly prefer that if it costs 25 gold and I don't have 25 gold, the recipe fails the same way it would if I didn't have an ingredient or an attendant, even if I have 3 platinum so I have enough total wealth to cover the cost.

I play in a few campaigns where precisely which coins you have matters for various reasons (weight, how much a thief steals from you by pickpocketing, etc.) so having all of the coin convert to platinum makes recipes with a crafting cost completely unusable.

**Comment by AngryBeaver** [comment]
Could be a fast solution.

I look into the bugs first and then i will see what else fits into my weekend.

**Comment by AngryBeaver** [comment]
should work now in 3.0.2 beavers-crafting and 2.0.0 beavers-system-interface and bsa-dnd5e 2.0.0
