### ISSUE TITLE
[Bug] Recipe information not showing

### ISSUE THREAD

**Issue by jcomplex** [AngryBeaver/beavers-crafting#48]
Summary
When I try to interact with recipes that the PCs know the details are not showing up the right side of the interface. I do notice an error gets throw everytime I click on one of the recipes on the left side of the interface. I am wondering if there is an incompatibility with Better Roll Tables as it also shows up in the error.

### Expected Behaviour
![image](https://user-images.githubusercontent.com/2319506/230743279-bb771fc5-08b4-4940-b4b7-83e20cbb4ca5.png)

### Actual Behaviour
![image](https://user-images.githubusercontent.com/2319506/230743249-d1d6e9a0-8be3-42b2-abbb-2e6425579762.png)

### Steps to Repro
1. Add a recipe and ingredients to PC Sheet
2. Click on Crafting tab on PC Sheet
3. Choose available recipe

### Versions
Module version : 3.1.1
Foundry version: 10.291
D&D 53 version: 2.1.5

**Comment by AngryBeaver** [comment]
thx for your report.
I will have a look.

**Comment by AngryBeaver** [comment]
yeah found something. We both extend functionality to the Handlebars framework which is global and lacks some basic methods. Our both modules extend an "isEmpty" method. 
As stupid as it is i think i will prefix my methods just to avoid collisions. will come in 3.1.2 soon

**Comment by AngryBeaver** [comment]
fixed and released

**Comment by AngryBeaver** [comment]
jfi: 
You actuall do not need to add the recipe to the pc-sheet you can just adjust the owner ship of the recipe to observer for the users that should have access to it. That way your actors are not overly polluted with recipes.

Giving a recipe to an actor sheet is a way for automate knowledge e.g. learning recipes via merchant. Or for onetime usages  e.g. you have a recipe that on use consume itself (has itself as ingredient) so you can actually only craft once with it.

**Comment by jcomplex** [comment]
Oh thank you so much for fixing that the information on recipes.
