### ISSUE TITLE
[SUGGESTION] Multiple Checks + Progress

### ISSUE THREAD

**Issue by 9ryex5** [AngryBeaver/beavers-crafting#5]
It would be useful to be able to make recipes that need multiple skill check successes to finish.
Also, useful to be able to track progress (for example if an item requires 3 checks and you succeeded on one you see 1/3).

Same for failure, maybe to fail to craft an item you need 3 failed checks, if you just fail once, you don't immediately lose the materials.

**Comment by AngryBeaver** [comment]
I am currently not convinced to do this
Reasons:
1) I personally do not see a benefit, or that this is a feautre lots of people are gona need.
2) It increases complexity in ui and data. e.g multiple checks require already at least a progressbar the result has to show the skill success fail somehow individually for all skills not like currently. Also if i introduce this people want to set up what happens with 1,2 3rd failed check. 
3) mostlikly will introduce a breaking change in the data structure -> old recipes might break.

Huge increase of complexity with for me currently relativly little gain or usability -> keep it simple possible. Maybe i will reconsider if multiple user request this, sry for now.

**Comment by 9ryex5** [comment]
The main reason for this suggestion is to support [Kibble's Craftin Guide](https://static1.squarespace.com/static/5e7eab9fcc76e2321541f8b3/t/63336ffa0dad1f5fa4e27d1e/1664315429118/Crafting+PDF+%28Free%29)

**Comment by AngryBeaver** [comment]
I will look into it but it is mostlikly pain to implement so it will currently have low prio.

**Comment by cadowtin** [comment]
Similar to above also would appreciate it for kibbles crafting guide, but understandable if low prio etc. Also am using Crash's Tracking and Training for 5e atm for craft progress tracking

**Comment by AngryBeaver** [comment]
Current Thoughts:
For this to work at all i would need to store the crafting process somewhere currently it is not.
Crafting is tied to an actor so probably at the actor data, visualisation probably becomming a new tab on actor.
I still do not need this i rather wanted to implement the time to craft but time to craft also needs to store something somewhere. So for time to craft i would need to think about this here to make them compatible.
  
Haveing a process means you want time between the rolls. Time between rolls means the crafting is not done instantly. When it is not instantly your inventar could change during the crafting process... .

problem: inventar changes durring crafting.
1.) crafting is also done in two steps: first it consumes everything then when done it produces everything.
2.) the process is a precrafting thing... when all rolls are done and you complete process then it consumes and produces everything as before.

1.) we have currently one macro that can handle consumption and production, this would need to get splittet, but both parts will be less powerfull then.
2.) feels strange... you could actually start a crafting process without all ingredients and then gather them just haveing them in time when doing the final check... hm well i could live with that.

i am currently bussy working on another module but i now have an idea how to taggle this. So i do not have frogotten you but it still is not high prio to me.

**Comment by AngryBeaver** [comment]
ok it is now out but got breaking changes so its within 3.0.x

**Comment by AngryBeaver** [comment]
with this update my module is no longer only about crafting it now can track and progress any downtime activity, run skillchallenges or quests.
