### ISSUE TITLE
Subtype Recipe

### ISSUE THREAD

**Issue by Denner09** [AngryBeaver/beavers-crafting#51]
Error creating subtype Recipe

I go in the module settings and change from "Create New Item" to "Recipe", but it does not appear in item creation.

**Comment by AngryBeaver** [comment]
Hi,
Yes this can't hardly work :-).
You missunderstood the configuration here.

You need to enter here the name of the title shown when you create a new item. For english foundry clients it is 

![image](https://user-images.githubusercontent.com/10677192/233388262-fd1722e8-f670-44c0-bcf2-de05afd4481e.png)

If you have a diffrent language your title will be diffrent.

In foundry v10 you usually can !NOT! really add new item types so i horribly fake one :-)
In reality im using another item type and wire my recipe on top of it for dnd it is "loot".

Anyhow if you do not see this in your item creation window you need to change this configuration you found to match your language
![image](https://user-images.githubusercontent.com/10677192/233389078-1f1b45a1-e49b-4a3f-b371-61016a28229c.png)

**Comment by AngryCrafter** [comment]
> ah probably figured it out already as it is closed just saw now :-)

I havent figured this out, your troubleshooting isnt clear.

**Comment by AngryBeaver** [comment]
For dnd5 since version v3.x the title name is diffrent to the window title ... so yes if you use this the troubleshootiing it is no longer correct. It was for this issue here will figure it out here:
https://github.com/AngryBeaver/beavers-crafting/issues/134
