### ISSUE TITLE
Possibility of an "or" feature on cost

### ISSUE THREAD

**Issue by leonelflg** [AngryBeaver/beavers-crafting#52]
Just created a github account to post this. Not sure if it's the right place.
Loving the module, but I'd love to see in the cost alternative on the cost of a recipe.
I think it will be easy to show what I mean. Something like the image.  [https://imgur.com/a/tVTzltC](url)

**Comment by AngryBeaver** [comment]
You might do something similiar with an anyOf item. But i understand that scripting a specific anyOf is not as simple. Also the usage is currently not best. Your aproach needs way more consideration how to scale ? how to choose ? how to allow brackets (a and b) or c vs a and (b or c). how to ui that. I need to think about it.

**Comment by leonelflg** [comment]
I saw the anyOf item, but honestly is way beyond my reach. I can't code, so I don't know how I'd use the anyOf. I'll try to think of something, to help in any way.

**Comment by AngryBeaver** [comment]
Just to keep your hopes down: Its rather complex and won't come anytime soon, that i already figure out. But I think i can and will do it at sometime. I keep you informed when i start working on it.

**Comment by leonelflg** [comment]
That's no problem at all. Wish I could help more. I'm trying to mess around with AnyOf meanwhile. And while I'm here, ever wonderer putting a 'spell usage' on the test, or something like that?

**Comment by AngryBeaver** [comment]
spell usage is really complicated especially for multi systems, i do not think it will come within the test selection but i enabled macros so anyone fancy enough can already do mostlikly anything with it. I have left a simple spell consumption macro in my documentation but i hadn't tested this part of my documentation recently.
https://github.com/AngryBeaver/beavers-crafting/blob/main/macros.md#simple-spell-consumption

**Comment by AngryBeaver** [comment]
or feature available now. for input, require and result data.
