### ISSUE TITLE
[Feature Request] Take 10

### ISSUE THREAD

**Issue by rayd99** [AngryBeaver/beavers-crafting#55]
I would like to see if there could be an option to "Take 10" on a craft. Which means that the GM can specify that instead of a roll, you can guarantee a roll result of "10", whether that be due to superior tools, feats, extra time, or because the GM says so.

**Comment by AngryBeaver** [comment]
I am sry but i do no think i will implement this.

**take 10:** 
you can kinda do so already:"normally" you should get a popup before you roll here you might enter any sitational bonus, i think some systems already have there a take 10 button. ("normally" -> i think in dnd midi-qol and settings  full automated will skip this popup as it is what you wish with those settings") 

**superioir tools** 
for dnd you can use a tool for a skillcheck. tools already can have bonuses so superior tools would be covered.
![image](https://github.com/AngryBeaver/beavers-crafting/assets/10677192/4db4b849-30bd-469d-9ee4-ccb69308ca17)
I am sry for other systems i currently can not offer this.

**feats, extratime**
yeah sry do not have anything automated for those but you can always argue with your gm and he might decide to give you situational bonus covered up in aboves take 10 section.
