### ISSUE TITLE
[Bug] Vanishing Spell

### ISSUE THREAD

**Issue by Panzybear** [AngryBeaver/beavers-crafting#56]
Whenever you (foolishly) make a new spell on an actor page, make a recipe item that uses that spell as the result, then craft that recipe as that actor, it puts the spell into limbo, and deletes it from the actor. As well as removing the "add a spell manually" text line. It looks like the spellbook still thinks its there in the list, so it's not showing the "no spell levels" text. But, it cannot be used or referenced since the spell is gone from the actor.
![image](https://github.com/AngryBeaver/beavers-crafting/assets/123211050/d6640f82-fb2f-4836-a888-e00ad0106772)

**Comment by AngryBeaver** [comment]
yeah you should not do this :-).
Spellconsumption is difficult. 
You can do something like it by adding it as required so it wont get consumed while you still need it on your char.
You then also can write a macro to consume a spellslot but it is not the same.

I will think about disallow dropping spells as cost. As this module is system independent it would mostlikly end up as configuration settings where you can disable items types of your  system.

**Comment by Panzybear** [comment]
Is there anyway to repair the character sheet? Or Is it always going to have that phantom spell?

**Comment by AngryBeaver** [comment]
sry. The data is gone you can't restore it. 
For reparing it there is no easy way. 
You might look into the char data and find what ever is left over that shouldn't be there.
module developer mode might help hier as you then gets a headline button to get a link to your char data:
![image](https://github.com/AngryBeaver/beavers-crafting/assets/10677192/d8af2c94-8db7-4a10-b46d-a3954997b62a)
hitting f12 will open console.
![image](https://github.com/AngryBeaver/beavers-crafting/assets/10677192/28116db7-8976-4765-8aae-05f5e42cdfa2)
click the link see the char data.

to change anything in there you need to get the id  of your char. 
![image](https://github.com/AngryBeaver/beavers-crafting/assets/10677192/0973e8db-ac56-45fb-9ef5-191795b389a4)
then scroll down to the console input. enter something like this:
game.actors.get("04rIz2xtUDc4yNsf")
you will again see the data of your actor.
you might now try to update anything on this actor manually: e.g.
game.actors.get("04rIz2xtUDc4yNsf").update({"name":"test"})

doint things like this might break the actor even more so be carefull.
