### ISSUE TITLE
[Bug] anyOf is not supported in PF2e. (Foundry v10)

### ISSUE THREAD

**Issue by relaytheory** [AngryBeaver/beavers-crafting#58]
The module will fail to evaluate anyOf ingredients.

This can be replicated by making an anyOf item with the macro (return item.system.source === "Ingredients.Mushroom").
Create an item and list the source as: Ingredients.Mushroom

The "Ingredients" and "Recipes" compendiums exist in the DnD5e version of the module, but do not exist in the PF2e version, thus I cannot test to see if your example anyOf items work.

I am running Foundry v10 - Stable, Build 291.

![Screenshot_4](https://github.com/AngryBeaver/beavers-crafting/assets/32248765/de2f4087-43db-4e7a-a293-f64b322dd04c)

**Comment by AngryBeaver** [comment]
![image](https://github.com/AngryBeaver/beavers-crafting/assets/10677192/b781c96b-f992-490d-b6b3-5ea66790a009)
![image](https://github.com/AngryBeaver/beavers-crafting/assets/10677192/e52f6a64-f455-4ac1-9a30-661b932562f2)

As it looks like the information in pf2e is wrapped one more time ... not sure why but thats up to the system.

If you are unsure about the values you can as seen in my screenshot always execute debug code like the console.log()

![image](https://github.com/AngryBeaver/beavers-crafting/assets/10677192/08bf8dfc-9d7c-46d3-95bf-7f2d044fdf68)

**Comment by relaytheory** [comment]
Adding the identifier "value" after "item.system.source" worked, thanks!
