### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by RonaldoBrum** [AngryBeaver/beavers-crafting#6]
How do you use the Any of type item? What is it for and how to apply it? Your module is amazing.

**Comment by AngryBeaver** [comment]
Yes, you are right i haven't documented that well, i should at a section to readme:

done:
https://github.com/AngryBeaver/beavers-crafting/blob/main/README.md#anyof

**Comment by RonaldoBrum** [comment]
Thank you very much ^^
