### ISSUE TITLE
AnyOf issue or feature request

### ISSUE THREAD

**Issue by tirzah2** [AngryBeaver/beavers-crafting#60]
Hi!
I love your module. 
I used AnyOf to allow players to craft leather armors with any kind of hide they find. Hides have different names, so i wrote:  return item.name.includes('Hide')
what i noticed tho is that the recipes for the player becomes available, but it still shows an X next to the ingredient (but i can craft) and i dont think it lets me select easily which hide to use if the player has more than one in the inventory (unless maybe i put it in the test field?)
maybe im not doing it correctly?

**Comment by AngryBeaver** [comment]
The anyOf is currently non functional for the precalculation i know that. you might consider it a bug but:

Usually you should be able to drag and drop an item of the actor inventar over the anyof replacing the anyof by this. see pictures:
[https://github.com/AngryBeaver/beavers-crafting#anyof](https://github.com/AngryBeaver/beavers-crafting#anyof)
 However recently i have got one report (haven't testet yet) that this is only available for gms.

There is already a feature request i want to do with the anyof to make it better usable.

On my next bigger change i am going to make a choice popup for any non resolved option when hitten craft. this is ment for the upcomming "or condition" on ingredients but it might work for anyof as well if the performance is not too bad. (would need to iterate over any "any of" and execute the macro for each item in actor inventar).

**Comment by AngryBeaver** [comment]
Thx for the reminder that i soon have to test that drag and dropping and fix it. If it is indeed broken. Also usually i think the anyof should neither show x nor success another thing i schould investigate

**Comment by tirzah2** [comment]
Thanks a lot. Your module is astonishing.
All my players are loving it. I'm looking forward to the anyof fix, now it's kinda usable, I just need to tell the players that is a bit glitchy and they need to pay attention at the moment but that it will be fixed eventually.

**Comment by AngryBeaver** [comment]
fixed the bug that players could not drop items on "anyOf" in the recipeCompendium. v3.1.7
The prio for the false x is lower and will come someday hopefully.

**Comment by AngryBeaver** [comment]
v3.2.0 has now a selectbox for anyof items
v3.2.2 has removed the precast "x" and replaced it with "?"
