### ISSUE TITLE
first time i open a sheet, crafting is not there

### ISSUE THREAD

**Issue by tirzah2** [AngryBeaver/beavers-crafting#65]
hi, i need to open the sheet twice to see the crafting tab:
this is the error the first time
![image](https://github.com/AngryBeaver/beavers-crafting/assets/83312683/a85075e7-a3f3-4adb-bf5b-dc71033396f0)

**Comment by AngryBeaver** [comment]
well the stacktrace hints towards the toolconfiguration.
![image](https://github.com/AngryBeaver/beavers-crafting/assets/10677192/bccc43d7-e935-43fc-845d-03a9b3107e8d)

Have you add tools in there ? possibly dropped a tool from an actor "yw3QIr..." and then possibly remove the actor or the tool item.

Plz check your config.
If you add tools there best drag drop them from a compendium or world items.

**Comment by AngryBeaver** [comment]
In the meantime you can kill all your tools... and then drop all of them from compendium else some recipes won't work.
F12 Console:
game.settings.set("beavers-crafting","toolConfig;"null);

Or F12 -> Sources
![image](https://github.com/AngryBeaver/beavers-crafting/assets/10677192/30979647-94d0-4e7a-bd2a-822784ad4847)
modules/beavers-crafting/src/Settings.js
![image](https://github.com/AngryBeaver/beavers-crafting/assets/10677192/2a021366-62e8-4ac8-bf52-3b3bd71936ae)
breakpoint behind toolConfig:
![image](https://github.com/AngryBeaver/beavers-crafting/assets/10677192/96aafc8d-279e-40c8-8a9b-fdbadf86c6df)

reload page wait for ending up in this breakpoint
F12 console
game.settings.set("beavers-crafting","toolConfig;",getSystemSetting().toolConfig);

will restore the default tools.

**Comment by tirzah2** [comment]
i might have added one.. but then i didnt it anymore so i probably tried to delete it?
i think my list of tools now is the original one. 
![image](https://github.com/AngryBeaver/beavers-crafting/assets/83312683/fc0483ea-1479-448c-9f0e-72e7b87e8f68)

**Comment by AngryBeaver** [comment]
i keep it open for feature:
autofix broken configurations

**Comment by AngryBeaver** [comment]
fixed in v3.2.2
