### ISSUE TITLE
(Problem) Dont show "RECIPE" in item menu.

### ISSUE THREAD

**Issue by FilipeValsoni** [AngryBeaver/beavers-crafting#68]
Hi,

I'm having a problem with the mod, I downloaded it, installed everything correctly, but when I go to create a recipe, the recipe option does not even appear in the item menu as shown in the video guide, I will attach some prints, with the mods I use and with the error.
Thanks if anyone can help me.

Tyyy, greate mod btw :D

![a](https://github.com/AngryBeaver/beavers-crafting/assets/140223657/05dc4121-cde8-4ede-bf65-b3d4b4b44f18)
![c](https://github.com/AngryBeaver/beavers-crafting/assets/140223657/11d438d9-d235-4af9-a845-e1907019a7bc)
![d](https://github.com/AngryBeaver/beavers-crafting/assets/140223657/18e9973e-97c5-4231-8b9e-f32317ee84f1)
![b](https://github.com/AngryBeaver/beavers-crafting/assets/140223657/c3c7071e-3851-4566-8f63-9f1e406b7202)

**Comment by AngryBeaver** [comment]
Well this is a reoccuring problem it seems :-) so i just added a troubleshooting [section ](https://github.com/AngryBeaver/beavers-crafting#dont-show-recipe-in-item-menu) into the readme:

plz verify that this is understandable and helps :-)

**Comment by FilipeValsoni** [comment]
> Bem, parece que este é um problema recorrente, então acabei de adicionar uma [seção](https://github.com/AngryBeaver/beavers-crafting#dont-show-recipe-in-item-menu) de solução de problemas no leia-me:
> 
> plz verifique se isso é compreensível e ajuda :-)

Ok, im so dumb ... hmmm.. sorry ?! :D

Solved, dont work Portuguese Brazilian, but ok, work fine in english.

THANKS <3

**Comment by AngryBeaver** [comment]
No not dumb you have been one  of many not finding it intuitive enough so i now have added that troubleshooting.
