### ISSUE TITLE
[Feature Request] Required Feature on PC

### ISSUE THREAD

**Issue by mnoreke** [AngryBeaver/beavers-crafting#7]
I'm not sure if it is feasible, but I would love the ability to restrict recipes based upon a feature added to the PC. I am running a heavy survival campaign, where they will need to gather materials to craft. But they also need the knowledge of how to do it.

To build a house, they need to make both the Foundation and the Framing. These are parts of the house they build. But rather than just requiring the Carpentry Tools, I also want them to know Construction.

I can add this as a custom skill, but I would end up with 15+ extra skills that way.

Alternatively, if a description could be added to recipes where text could be input on prerequisites (linked to items?) to learn the recipe, that would work as well.

**Comment by AngryBeaver** [comment]
you can handout recipes to the users inventory. Then they can use it by clicking on it, as far as i know. But it would not currently appear in the "crafting compendium". I may implement that it do though. 

That way they need to learn recipes by picking them up, is that something that would help.

**Comment by mnoreke** [comment]
That part I already know about, but I want to add requirements outside of tools to be used. A "Feature" type from Foundry if you will.

So either a description box (useful either way), or ability to require other items beyond tools on the character to utilize it.

**Comment by AngryBeaver** [comment]
Added attendants 0.7.x:
https://github.com/AngryBeaver/beavers-crafting/blob/main/changelog.md

**Comment by AngryBeaver** [comment]
This feature will pop up an issue quite soon: i'll likly have to soften my identity check. As most dnd games will use dndbeyond importer to get their classes and features but the main module of mr primate does not support the dnd5e core flag sourceId. That means the recipes wont match the classes and features of the user. Maybe something for next weekend.
