### ISSUE TITLE
AnyOf quantities

### ISSUE THREAD

**Issue by tirzah2** [AngryBeaver/beavers-crafting#70]
Hi,
maybe im blind, but i dont understand how to increase the anyof quantity in case a craft requires for example 10 hides of any kind.
![image](https://github.com/AngryBeaver/beavers-crafting/assets/83312683/5a22e819-719b-42f9-84da-c149a7bf1c81)
before i used to drag 10 times an hide on the UI, now if i do it, it creates 10 separate AnyOf Hide

**Comment by tirzah2** [comment]
p.s. in general now i cant increase quantities anymore by just drag and dropping. I have to first increase the quantity of the item and then drop it on the recipe (most of my items are in compendium so it might make it difficult to do)

**Comment by AngryBeaver** [comment]
fuck yes damn... you are right :-) ups.
Workaround for now:
 you can still do it when you change the quantity of the dragged item but yes i need to fix that assap.

**Comment by AngryBeaver** [comment]
ok just checked it is not as bad in general you can still increase the amount by dropping into the or section. 
If you drop the same item in an or condition it would not make sense to have it a seperated item that you can choose of as there is no choice both are the same the programm will just interprets it as 2 times the item.

That may not seem intuitiv at first but each "and" section is basically another group in each group you could have the same item without them joining. As only this results in groupA  item1 or item2 groupB item 1 -> you need at least 1 item1 instead when i would join them it would be item1 2times or item2 wich is not the same.

Still it is broken for AnyOF and needs to get fixed asap

**Comment by AngryBeaver** [comment]
you can now edit the quantity 3.2.1
