### ISSUE TITLE
[Feature Request] - Produce items based on DC check

### ISSUE THREAD

**Issue by JackaldaJester** [AngryBeaver/beavers-crafting#73]
Hello,

I'm not sure if this is currently possible, but I'd like to see the following function:

Player beats the DC by 10 so 1 item is produced OR;
Player beats the DC by 15 so 2 items are produced OR;
Player beats the DC by 20 so 3 items are produced

I find this useful for making food recipes or if they're gathering how many items they find.

**Comment by AngryBeaver** [comment]
Well this will never come in handy ui clicky easy ways as it is super complex. First of you could have multiple skills and each would have diffrent skill levels so with a tool its easier and without harder and then you might have multiple produced items which one should be combined to which skill etc there are too many possibilities to make this a good ui.

So no things like this will probably never make it into the ui. But macros could do what you want. Well sadly not the macro system i currently have implemented (as it is executed bevore skill checks) but i wanted to do implement advanced macros at some point anyway. 

AdvancedMacros:
This however will not come soon as it is not easy and comes with breaking api and probably a 4.x.x release.

For now sry it wont come the easy way.
But keep a look out for 4.x.x release it will probably be advanced Macros.
