### ISSUE TITLE
Issue - duplicate recipe strange behaviour

### ISSUE THREAD

**Issue by tirzah2** [AngryBeaver/beavers-crafting#74]
Hi!
So, yesterday something strange happened.
I don't have screenshots of it but I can explain roughly the situation.
A player finds an item called vial of the basilisk.
I decide to create a recipe on the spot called antiparilisys.
I copy an existent recipe called antitoxins, i change the required ingredients and the resulting product.

Some players see the new recipe perfectly.
Some players see the new recipe name correctly, but the recipe sheet is the same as antitoxin.

In order to fix it, I had to create a new antiparilisys potion from scratch, instead of duping antitoxin.

**Comment by AngryBeaver** [comment]
Well i assume the following. When you copied the recipe you also copied the ownership this means everyone could see instantly the new copies recipe.

ItemSheet is a foundry FormApplication and probably one that has set submitOnChange:true. This means every change on every input will get submitted.

So when your players now meantime open a RecipeCompendium they will copy the actual version of the sheet over. Some will have opened while you edited it. IF they then start crafting this recipe that recipe copy is stored on their actor as active crafting.

I recommend setting the ownership at the very last. Also i believe that when players reopen the RecipeCompendium all recipes gets refreshed.

**Comment by tirzah2** [comment]
we tried to refresh it but it was still a dupe of the antitoxin. 
but definetely now i will be more cautious when i create recipes on the fly when players are in game. 
thanks for the heads up :)

**Comment by AngryBeaver** [comment]
well i just verified that with every open of RecipeCompendiums all Recipes get refreshed by executing:
	static getAllItems() {
		// @ts-ignore
		return game.items.directory.documents
			.filter(item => Recipe.isRecipe(item))
			.map(item => Recipe.fromItem(item));
	}
	
So when you got issues as described, I guess a client gets outdated to the original data. 
But That is on foundry level i just access the foundry game.items object and assume everything in there is in sync.
-> Can't do any good here.
