### ISSUE TITLE
Feature Request - Dynamic DC and Optional Ingredients.

### ISSUE THREAD

**Issue by VulpTheKangaFox** [AngryBeaver/beavers-crafting#79]
Heya. Bit new to Foundry Macros and Javascript overall, so let me know if I'm not seeing something here. 

I'm using KibblesTasty's crafting rules, and creating recipes has been going fine up until the blacksmithing recipes. These ones are highly modular, and my intention with implementing them was to be able to craft lets say... A dagger. To craft the dagger you could use any metal, and depending on which metal was used it'll vary the check and output. Steel being the standard of course.

For example, if I wanted a bronze dagger, I'd throw in the necessary ingredients including the ingot. I'd check the ingot via the recipe macro and be able to output a modified version of it with the stats for a bronze tool, but it also requires me to be able to apply a -3 to the crafting DC. Of course, this would be circumvented by making separate recipes for each material, but that both increases clutter and decreases performance with so many recipes, and part of me worries just how long that might take. 

I had tried to use macros to modify all the DC fields I could find, but each one seemed to tweak the overall recipe item's DC, not the single instance of the recipe in the player's sheet.

Moving over to the pitch for optional ingredients, there's also something in KibblesTasty's crafting that allows for silvering or applying magical materials to the smithing process in order to buff the end result, such as silvering a weapon or applying a +1 modifier akin to a +1 weapon. But there doesn't seem to be any way to create optional fields for the crafting recipe, and I'm not even sure where to start with trying to make it via the macro or if it's possible.

Either way, thanks for your time and the awesome module. Even if it doesn't cover all of my needs, it's still been amazing to use and is a massive help with my game. 👍

**Comment by AngryBeaver** [comment]
hi, well for the first dynamic DC part that might be already possible but you would need to dive deep into javascript and my module interfaces.
The current macro execution time is placed before a crafting check is done and the result is given so you might modify the check based on the ingredient and modify the output also based on it.


You would need to have either optional ingots for each type or an anyOf item detecting any ingot.
then you need a macro manipulating the result:
https://github.com/AngryBeaver/beavers-crafting/blob/main/macros.md
and the recipe for manipulating the dcs.
recipeData.tests ...etc have a look at the types:
https://github.com/AngryBeaver/beavers-crafting/blob/main/src/types.ts

"I had tried to use macros to modify all the DC fields I could find, but each one seemed to tweak the overall recipe item's DC, not the single instance of the recipe in the player's sheet."

Not sure what you mean by this: when you access the arguments within the macro only that instance is manipulated no real Recipe Item is. When you craft on an actor an instance of the recipeItem is copied to the actors.crafting tab this instance should be independent to the recipe Item that is either located global or in the inventory of your actor.

BUT ! The current macros are a bit fragile. They depend to much on internal dataStructure and may break when i change the dataStructure. e.g. the recipeData previously stored the check under "skill" which allowed only one test and has then moved to "tests" <- will break macros manipulating the old skill attribute.
Also i already know that i will at some day implement advanced macros with multiple execution times and simpler but more robust arguments. this will possible break all current macros (will probably not come this year).


The optional ingrident part will probably not come 
Optional does only make sense when the optionality then activates something ( like what you have written changing the result or the dc etc) designing an understandable ui/interface for such relations is really complex if at all possible and given the rare usecase would be too much trouble for the gain this feature would bring (well at least in my opinion and my opinion will rate the feature up or down :-)).
So if at all optional ingridients will be purely optional ingridients without any functionality. So to make full use of it you would need to write a macro checking for the optional ingredients. -> this weakens the feature optional ingredient as without macro it won't have any effects, else then consuming any additional given ingredient beyond what is needed.

**Comment by AngryBeaver** [comment]
hm for your usecase of  optional e.g. your silver dagger you may do it slightly diffrent:

Just add  a recipe that silvers a dagger. You could do so for either all daggers or only for daggers that you have crafted previously making it consecutive recipes.

https://github.com/AngryBeaver/beavers-crafting/issues/61

**Comment by MasterCroissant** [comment]
Hi!

I'm also very interested in Dynamic DC since I use a crafting guide that modify the crafting DC of a recipe base on the rarity of the item used for the craft. For example, if one of my players wants to craft a Flame Tongue longword, doing so with a poor quality ingredient (i.e. a "common" rarity item) would give her a -5 bonus to the check. However, if she can get her hands on, namely,  "The Very Dangerous and Flaming Crown of the Nine Hells" (i.e. a "legendary" item), then she would get a +10 bonus to the check. I would love to see that being implemented one day, since all the recipes in this guide work with this kind of mechanic.

**Comment by AngryBeaver** [comment]
when this come it will not come as a hook i guess. As i interpret hooks as mainly for other developers and even more demanding then some "tiny" macros.

**workaround i had in mind does not work**: 
As i prevented the macro from manipulating the recipe by giving it a serialized clone of it :-)
Maybe i open up this a a bit more BUT !! be aware that i don't like mymakro structure anymore it is old and will be subject to some major changes someday.


**here is how it would have worked**

Assumption you have an anyOf "anyMetal"
and a recipe with that anyOf as first input and one test  only in it lest say the "arcana" skill with a basic dc of 8.
![image](https://github.com/AngryBeaver/beavers-crafting/assets/10677192/59a0411c-7b99-41a6-abb7-bfdf5bb65de4)

```
{
    "beavers-crafting": {
        "subtype": "Recipe",
        "recipe": {
            "required": {},
            "input": {
                "1": {
                    "tmZjMQu18qdY3dTJ": {
                        "id": "6DVvl8A5edOMzCpz",
                        "uuid": "Item.6DVvl8A5edOMzCpz",
                        "img": "modules/beavers-crafting/icons/anyOf.png",
                        "type": "AnyOf",
                        "name": "AnyMetal",
                        "quantity": 1,
                        "itemType": "loot",
                        "flags": {
                            "beavers-crafting": {}
                        }
                    }
                }
            },
            "output": {
                "1": {
                    "Compendium-dnd5e-items-Item-0E565kQUBmndJ1a2": {
                        "id": "0E565kQUBmndJ1a2",
                        "uuid": "Compendium.dnd5e.items.Item.0E565kQUBmndJ1a2",
                        "img": "icons/weapons/daggers/dagger-jeweled-purple.webp",
                        "type": "Item",
                        "name": "Dagger",
                        "quantity": 1,
                        "itemType": "weapon",
                        "flags": {
                            "beavers-crafting": {}
                        }
                    }
                }
            },
            "instruction": "",
            "tests": {
                "fails": 1,
                "consume": true,
                "ands": {
                    "1": {
                        "hits": 1,
                        "ors": {
                            "1": {
                                "check": 8,
                                "type": "skill",
                                "uuid": "arc"
                            }
                        }
                    }
                }
            }
        }
    }
}
```

macros are executed after the recipe is customized so after you have choosen what input you will use.
basically you then have a recipe for each of your metal but still all with the same dc.
![image](https://github.com/AngryBeaver/beavers-crafting/assets/10677192/abf80c38-6cb5-46f9-92d1-b0b22e60c5ca)

now you need to exchange the outcome and the dc within your macro.
!BE aware that the macro structur is old and i do not like it anymore and it will get reworked at someday!

The macro has access to recipeData. This will hold the actual customized copy of the recipe that is input of your crafting process. 
The macro has access to result. This will hold the actual crafting process. 
At the moment the macro is executed no test had been made so the test information is still completly on the recipeData.
```
input:{
    "1": {
        "Actor-VW1FcUq6VKgIOAH3-Item-yjWABmKE3S5iJ37i": {
            "id": "yjWABmKE3S5iJ37i",
            "uuid": "Actor.VW1FcUq6VKgIOAH3.Item.yjWABmKE3S5iJ37i",
            "img": "icons/commodities/metal/ingot-stamped-silver.webp",
            "type": "Item",
            "name": "Iron",
            "quantity": 1,
            "itemType": "loot",
            "flags": {
                "beavers-crafting": {}
            }
        },
        "-=tmZjMQu18qdY3dTJ": null
    }
}
```
while it is probably a reference bug that we have a foundry delete syntax inside the recipeData we still can use it like so:

```
//first non null element of first input.
const metalObject = Object.values(Object.values(recipeData.input)[0]).find(i=>i!==null);
console.log(metalObject);
if(metalObject.name === "Iron"){
  //first and + or test
  Object.values(Object.values(recipeData.tests.ands)[0])[0].check = 12;
}
```
but !! the recipeData manipulated will not make it back as i obviously intended to only use the result variable as input/output :-/

**Comment by AngryBeaver** [comment]
you can now do so:
[macro](https://github.com/AngryBeaver/beavers-crafting/blob/main/macros.md#dynamic-dcs)

removed the savety readonly recipeData you now have the recipe Object itself still best only manipulating the recipeData interface.

**Comment by p4535992** [comment]
This ticket can be closed i confirm now is possible do this with the API.
