### ISSUE TITLE
Currency Conflicts

### ISSUE THREAD

**Issue by Kurinitus** [AngryBeaver/beavers-crafting#80]
I've noticed that this Modules reacts negatively to the removal of Currencies in the world.json. I had Electrum removed and because of that the module refuses to propogate the Recipe Menus where you put in ingredients and costs. It makes me wonder if more currencies were added if it would also flag the same issue.
![image](https://github.com/AngryBeaver/beavers-crafting/assets/143648769/333ff2fc-14ae-473d-a19c-d24276af7929)
I've since removed that compromising code line in the Conversion and it goes back to working properly. Is there a means to make the module work without electrum being required?

**Comment by AngryBeaver** [comment]
Well currency conversion is done in beaver-system-interface or if it is specific to a system in the system specific adaption modules. As far as i have read you had this problem for dnd5e those adaptions are farily simple.

I have no knowledge about tinkering world.json. but yes in dnd5e i took the easy way and use hardcoded lines for the currencies: https://github.com/AngryBeaver/bsa-dnd5e/blob/main/src/Dnd5e.ts.
I can have a look soon when i am back from my vacation should be possible to read it from the global CONFIG variable or something like that.

**Comment by Kurinitus** [comment]
It might be because of the custom numbers I have here on my side also conflict with the hard numbers you have here. Sorry, yes it was indeed for 5e. 

Hooks.once("init", () => {
  CONFIG.DND5E.currencies.sp.conversion = 5; // 1gp = 5sp
  CONFIG.DND5E.currencies.cp.conversion = 25; // 1gp = 25cp
  CONFIG.DND5E.currencies.pp.conversion = 0.2; // 1gp = 0.2pp
  delete CONFIG.DND5E.currencies.ep;
});

Take your time and enjoy yourself! I'm already over the moon for you being able to at least take a cursory glance/assumption of the potential issue.

**Comment by AngryBeaver** [comment]
bsa-dnd5e v2.0.2 released this should help you.
https://github.com/AngryBeaver/bsa-dnd5e/releases/tag/v2.0.2
