### ISSUE TITLE
 Help Request

### ISSUE THREAD

**Issue by Xeonis** [AngryBeaver/beavers-crafting#83]
Hello, I write a little code, and I didn’t find how to contact you, so I’ll ask in "issues" 
I can help you with the module?
Discord (xeonis)

**Comment by AngryBeaver** [comment]
At the moment my main attention is on another module and i am mostly tiered from work during the week so my spare time for vtt-foundry modules are anyway a bit low. 

If you want to contribute you can always fork this project and then create a pullrequest. (for bugfixes anyway for features that needs to be aligned with my vision upfront ).
If you want to help with a feature you may have a look at https://github.com/AngryBeaver/beavers-crafting/issues/64
that should be a low hanging fruit and is required to be done before: https://github.com/AngryBeaver/beavers-crafting/issues/81.

You might also contribute by implementing a bsa-x implementation for a another system not yet covered. Those implementations are rather small and are completly standalone.
https://github.com/AngryBeaver/beavers-system-interface/wiki/BSA-x-links

**Comment by Xeonis** [comment]
That’s why I’m asking permission + I want a contact to discuss features and other things outside of github

**Comment by AngryBeaver** [comment]
Hm yeah i am sorry that sounds more stressfull then helpfull for me. It more or less sounds like my worklive. Coordinate work create concept stories and reintegrate parts and there after fix the bugs left over :-/. 
I just wanted something simple for fun and to relax from work. I am sorry but i am just not the right guy for that.
