### ISSUE TITLE
[PF2e] System has altered source directory.

### ISSUE THREAD

**Issue by relaytheory** [AngryBeaver/beavers-crafting#84]
PF2e has made changes to clarify an item's source.
Unfortunately, this has made the "AnyOf" script no longer compatible with the system.
The "AnyOf" test box also no longer works, dragging items into the "drop item" test box has no effect.

All existing "sources" have been migrated into the Publication box of the original source location.

![Screenshot_8](https://github.com/AngryBeaver/beavers-crafting/assets/32248765/ac4a3017-b006-4e99-9fdf-ee81ce3f6e49)
![Screenshot_7](https://github.com/AngryBeaver/beavers-crafting/assets/32248765/cb7300f6-a14c-4fab-83fd-71c206b9af50)

Foundry v11 Stable
Build 308
Pathfinder Second Edition v5.7.1

Beaver's Crafting Module v3.2.4
Beaver's System Interface v2.1.4
Beaver's System Adaptation pf2e v1.0.1

![Screenshot_6](https://github.com/AngryBeaver/beavers-crafting/assets/32248765/21b5620c-f92f-4d5c-9041-f239ef9b0c12)

**Comment by AngryBeaver** [comment]
Well it lookt to me that it breaks inside an anonymous method which probably is the user macro given here.

The anyof lets you define a macro and is user specified e.g. not within any code i have control over there could be anything anyone has entered same when you would have written a recipe macro or i guess every macro written. 

You probably have to adapt your macro code accordingly to the new rules of your system, there is not much i can do as i do not write or own the macros placed there.

If you have lots of places you might try to do this automatically. Probably you would need to open up console iterate over all items find and replace specific code with new syntax and store all items touched this way.

probably something like this:
game.items.filter(i=>i.flags["beavers-crafting"]?.subtype === "AnyOf").forEach(i=>{const replaced = i.flags["beavers-crafting"].anyOf.macro.replace("test", "after"); i.update({"flags.beavers-crafting.anyOf.macro":replaced})});

this replaces "test" with "after" on all AnyOf but as said i do not know what everyone has written there so i can not provide any fix. ... i guess.

**Comment by AngryBeaver** [comment]
be very carefull :-) with this iteration and automatic updateing of all your items you may break them if not done correctly.

**Comment by relaytheory** [comment]
The macro actually used to work!
Before PF2e updated how it listed its source, the macro you provided on your GitHub worked fine.
It used to look like this, so the macro worked fine.
![Screenshot_2](https://github.com/AngryBeaver/beavers-crafting/assets/32248765/43516a13-e6f0-4be3-bd4c-ff17b1af9a63)

The "drop item" test box worked back then too, but now, dragging items into the "drop item" box no longer works.

If it is a macro issue, I'll try to search for documentation on my end.
Any direction you could point me in, potentially?

**Comment by AngryBeaver** [comment]
Well ofc it used to work but the system updated so the macor now is incompatible.
The drop item still works but your macro now creates an exception thus can not do anything.
My system is still functional here it just executes everything anyone has put there e.g. just put this line there:
ui.notifications.info("hello world")
and it will popup "hello world" it executes what ever the user puts in there !


Just change the line item.system.source.value to the one the system needs now.

If you do not know the current system datamodel you might want to just write console.log(item) into the AnyOf macro.
Then hit f12 and drop something to test against your marcro. It should work and print the structur of the item into console.
then just find the new path your attribute has moved to and change your anyOf macro again into something that returns true when the item on that path equals the value you want.

![image](https://github.com/AngryBeaver/beavers-crafting/assets/10677192/208a7969-ab66-49f1-8e78-f6042976fadf)

![image](https://github.com/AngryBeaver/beavers-crafting/assets/10677192/d96882a9-167c-4518-bbb0-15f8aa690145)

So if you want to detect your item by publication you can do so by: return item.system.publication.title === "Mushroom"

But you could as well type something like return item.name.includes("Mushroom") when you want all items that have Mushroom in its name.

**Comment by relaytheory** [comment]
Thanks for the guidance!
