### ISSUE TITLE
Using Subskills for checks

### ISSUE THREAD

**Issue by Kubixcube** [AngryBeaver/beavers-crafting#85]
Is there a way to use a "subskill" as a check for crafting ?
For example, in Pathfinder 1, I want to use the subskill Craft(**Cooking**) but I can only select Craft in the recipe interface. Thus, there will never be points invested in Craft when the roll is made.

**Comment by Kubixcube** [comment]
Okay, no prob ! Thanks for all your work, it is already amazing !

**Comment by AngryBeaver** [comment]
try v1.0.2 bsa-pf1
https://github.com/AngryBeaver/bsa-pf1/issues/1
