### ISSUE TITLE
Beaver's Crafting forge compatibility issues

### ISSUE THREAD

**Issue by OnegoodgreekDM** [AngryBeaver/beavers-crafting#88]
<img width="850" alt="Screenshot 2023-11-30 at 12 38 55 PM" src="https://github.com/AngryBeaver/beavers-crafting/assets/68712391/7239ad35-b9f6-41e8-ac22-db4f30486e61">

Hi there, this module is probably one of my absolute must haves and favorites for Foundry. I just updated to the new DND 5e system and keep getting this message. I have updated every module and restarted the game multiple times. I just wanted to let you know how much we use this module in our game. I have created hundreds of unique ingredients, parts, component etc which I add to monsters, chests etc and have given my worlds an incredible amount of storytelling depth and my players a lot of enjoyment, wonder and a level of gindyness for materials they really enjoy. Are you planning on updating it? Also, if there is a Patreon or Discord server you run, let me know. I'd love to support this module. Thanks for everything you do!

**Comment by OnegoodgreekDM** [comment]
<img width="850" alt="Screenshot 2023-11-30 at 12 42 11 PM" src="https://github.com/AngryBeaver/beavers-crafting/assets/68712391/88f265a2-c700-4ed3-a1aa-255d704447d1">
Attaching the actual message shown in Foundry here

**Comment by AngryBeaver** [comment]
Thanks for your report i will have a look. 

I guess there is just one of its dependencies missing, maybe try deinstall and install the module again then it will popup a dialog to install also all dependencies.

**Comment by AngryBeaver** [comment]
v11 seems to work with the latest dnd5e: 2.4.0

![image](https://github.com/AngryBeaver/beavers-crafting/assets/10677192/b854b3fc-240b-48e7-8493-950579e57ff0)

try to update/install and activate all those 3 modules checked in the picture above. I hope foundry will improve notification here at someday so it shows witch dependencies are missing.

**Comment by AngryBeaver** [comment]
and again i just did see i was behind with my v11 instance:
![image](https://github.com/AngryBeaver/beavers-crafting/assets/10677192/c1d8a7b1-e3c7-4340-9bff-b725baa3be50)
but should work non the less.

**Comment by OnegoodgreekDM** [comment]
Hi again, and thanks so much for the quick response! I tried again, and I still get the message above. I forgot to mention that I use The Forge and I wonder if the issue is due to this. Thoughts? Otherwise I have updated to the most recent verion of Foundry pushed by Forge. Thanks again.

**Comment by AngryBeaver** [comment]
what are your versions for the other two modules above bsa-dnd5e and the system interface ?

**Comment by OnegoodgreekDM** [comment]
Thanks again for your response. v11 - Foundry, dnd5e system: 2.4.0. I cannot enable the other two modules. I can reach out the Kokorotoro the Forge Leade Dev to see why this is happening as well on Discord.
