### ISSUE TITLE
Feature Request - Add on the recipe the ability to set an explicit name for the final object, so as to avoid the issue of merge of crafted objects and not 

### ISSUE THREAD

**Issue by p4535992** [AngryBeaver/beavers-crafting#91]
Add on the recipe the ability to set an explicit name for the final object, so as to avoid the issue of merge "crafted objects" and "not crafted" as indicated here: https://github.com/AngryBeaver/beavers-system-interface/pull/13 use case for use case

**Comment by AngryBeaver** [comment]
on it. I am currently testing some more complicated solutions. Maybe i got the time to finish it on the weekend.

**Comment by AngryBeaver** [comment]
seems to work also with the asymetrical extension for isSame.

As it has imrpoved complexitiy i need some testing time especially the styleing is currently not based on system interfaces thus will probably break on some.
Also needs some documentations.

Sum up it works like you original wanted it to work ! but this new asymetrical isSame method will probably not work correctly in combination with other modules that interact on items and are not based on bsi e.g. itemPiles
