### ISSUE TITLE
[Feature Request] Fallout 2d20 Compatibility

### ISSUE THREAD

**Issue by WyntherKnight** [AngryBeaver/beavers-crafting#92]
Hi, 

Fallout is known for its crafting and modding, any chance of a compatibliity with Fallout 2d20? 

Thanks.

**Comment by AngryBeaver** [comment]
1.)it is not always possible for all systems so I can not guarantee that this will do.
2.) currently this is low prio for me and I have a lot of work. I might have a look and do it if it is simple.

Best would be if you can ask someone with developer skills that is already using or modeing that system to write the bsa-x adaption layer ~ 100lines code and quite simple if you know the system :-). 
https://github.com/AngryBeaver/beavers-system-interface?tab=readme-ov-file#how-to-write-bsa-x-implementations

Take a look at the existing bsa-x implementations: e.g. pf2e: https://github.com/AngryBeaver/bsa-pf2e/blob/main/src/Pf2e.ts

**Comment by WyntherKnight** [comment]
Thank you!
I'll look into having someone who can code this. 
I know that it's not a priority for you, but yeah, if you can get chance, please look into it, 
Thanks again. :)

**Comment by AngryBeaver** [comment]
Well i created a pr for the system designer to make a basic adaption possible. But this system behaves diffrently on some levels: my module expects skill tests to return one success or one failuer when not reached a given threshold. 

fallout might return multiple success and or failures within on roll (after pr) -> so an adaption for this system will be you can set a threshold how many success you need and it will succes when you hit the amount of success and fail a craft when you do not. 

I am unsure about the roll failures so i will ignore them ?

**Comment by AngryBeaver** [comment]
![image](https://github.com/AngryBeaver/beavers-crafting/assets/10677192/a38f066c-688f-49cb-8860-804d291908da)

**Comment by AngryBeaver** [comment]
Well it might be possible but does not match good for this system.

The dc on recipes reflects the amount of successes needed with one roll. Also failures or what ever that is in this system does have no effect.

needed this PR to land:
https://github.com/Muttley/foundryvtt-fallout/pulls

**Comment by WyntherKnight** [comment]
Hey, thanks for looking into this. Really appreciate it.

**Comment by AngryBeaver** [comment]
PR is merged and fallout 2d20 is now also public included with v3.5.0

**Comment by WyntherKnight** [comment]
Thank you so much this! Cheers!
