### ISSUE TITLE
[BUG]  Exception during crafting when setting "Separate crafted Items=Partial" and component is not crafted

### ISSUE THREAD

**Issue by p4535992** [AngryBeaver/beavers-crafting#97]
The use case i have a reciper for a Dagger:
- 1 Tools
- 1 Iron Lingot (with flag "isCrafted" false)
- 1 Dagger as item result

![](https://i.imgur.com/bjiKYLJ.png)

And the module settings"Separate crafted Items" with value "Partial".

I got a error

![](https://i.imgur.com/EHi870c.png)

on this line: 
https://github.com/AngryBeaver/beavers-system-interface/blob/26049e94dc20f31f687af2d97fc6fb955b15fd32/src/CoreSystem.ts#L361

because this condtion fail:
https://github.com/AngryBeaver/beavers-system-interface/blob/26049e94dc20f31f687af2d97fc6fb955b15fd32/src/CoreSystem.ts#L349C33-L349C33

in the specific :

- `c.isSame(component)` = false
- `component.isSame(c)` = true

So i have try to fix by adding `!bHasFlags` on this line :
https://github.com/AngryBeaver/beavers-crafting/blob/6802edb34f99f390a218f1a84de121098d641e40/src/main.js#L64C36-L64C37

but after this patch the two objects _Dagger not crafted_ and _Dagger crafted_ are merged by quantity ?

**Comment by AngryBeaver** [comment]
thx for the detailed instruction i will try to find out what is going on.

**Comment by AngryBeaver** [comment]
kk 

in partial mode: when the recipe has not falgged something as crafted it will use and prefer non crafted but will also use crafte ingridients. 

so i guess your inventar had steel ingot but only crafted once and my algorithm assumed there would always be any equivalent if i have found anything on actor this is a wrong assumption right in the first line you send.

The beavers-crafting extension of isSame should still be correctly asymetrical:
(!aHasFlag || aHasFlag === bHasFlag) => when a does not have a flag or when a is flaged b has to be flagged too.
-> this will result in my partial definition that a recipe without flags will also use flagged items but a recipe with flag will only use flagged items.

I will fix the line and test it someday tomorrow.

**Comment by AngryBeaver** [comment]
should be fixed with 2.1.7 beavers-system-interface
